package org.weaveos.workflow;

import static org.junit.jupiter.api.Assertions.*;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.UUID;
import org.flowable.common.engine.api.FlowableObjectNotFoundException;
import org.flowable.engine.ProcessEngine;
import org.flowable.engine.ProcessEngineConfiguration;
import org.flowable.spring.SpringProcessEngineConfiguration;
import org.flowable.task.api.Task;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;

/**
 * Root-authored engine compatibility experiment, not a product execution port.
 * All rows/processes are synthetic and confined to this test's random schema.
 */
class RootReturnCompatibilityTest {
 static String id(int n) { return String.format("%08x-0000-4000-8000-%012x",n,n); }
 static String node(int n) { return "n_"+id(n).replace("-",""); }
 static String roster(int n) { return "a_"+id(n).replace("-",""); }
 static final String VERSION=id(100);
 JdbcTemplate admin,jdbc; DataSourceTransactionManager tm;
 ProcessEngine engine; DeploymentRegistry registry; String schema,process;
 @BeforeEach void setup() throws Exception {
  String url=System.getenv("B3_TEST_JDBC_URL");
  assertEquals("jdbc:postgresql://b3-postgres:5432/b3_flowable_fixture",url,
   "Only the dedicated unexposed synthetic database may run these tests");
  admin=new JdbcTemplate(new DriverManagerDataSource(url,"b3_fixture","b3_fixture_only"));
  schema="v030_return_"+UUID.randomUUID().toString().replace("-","");
  admin.execute("CREATE SCHEMA "+schema);
  var ds=new DriverManagerDataSource(url+"?currentSchema="+schema,"b3_fixture","b3_fixture_only");
  tm=new DataSourceTransactionManager(ds);jdbc=new JdbcTemplate(ds);
  var c=new SpringProcessEngineConfiguration();c.setDataSource(ds);c.setTransactionManager(tm);
  c.setDatabaseSchema(schema);c.setDatabaseSchemaUpdate(ProcessEngineConfiguration.DB_SCHEMA_UPDATE_TRUE);
  c.setAsyncExecutorActivate(false);c.setDisableIdmEngine(true);c.setDisableEventRegistry(true);
  engine=c.buildProcessEngine();registry=new DeploymentRegistry(jdbc,tm,engine);
  try(var in=getClass().getResourceAsStream("/deployment-registry-fixture.sql")){
   assertNotNull(in);jdbc.execute(new String(in.readAllBytes(),StandardCharsets.UTF_8));
  }
 }
 @AfterEach void cleanup(){
  if(engine!=null)engine.close();
  if(admin!=null&&schema!=null)admin.execute("DROP SCHEMA "+schema+" CASCADE");
 }
 void start(String mode) throws Exception {
  String xml;
  try(var in=getClass().getResourceAsStream("/return-compatibility/return-"+mode+".bpmn20.xml")){
   assertNotNull(in,"must be generated by the actual Go compiler");
   xml=new String(in.readAllBytes(),StandardCharsets.UTF_8);
  }
  var receipt=registry.deploy(new DeploymentRegistry.Request(id(101),id(102),VERSION,1,xml));
  var vars=new HashMap<String,Object>();
  vars.put(roster(2),List.of(id(8),id(9)));
  vars.put(roster(3),List.of(id(10),id(11),id(12)));
  vars.put("wf_rejected",false);
  process=engine.getRuntimeService().startProcessInstanceById(receipt.processDefinitionId(),vars).getId();
  assertTasks(2,Set.of(id(8),id(9)));
 }
 List<Task> tasks(){return engine.getTaskService().createTaskQuery().processInstanceId(process).list();}
 List<String> ids(List<Task> tasks){return tasks.stream().map(Task::getId).sorted().toList();}
 Task assigned(String actor){return tasks().stream().filter(t->t.getAssignee().equals(actor)).findFirst().orElseThrow();}
 void complete(String actor){engine.getTaskService().complete(assigned(actor).getId(),Map.of("wf_rejected",false));}
 void reachSecond(){complete(id(8));assertEquals(1,tasks().size());complete(id(9));assertTasks(3,Set.of(id(10),id(11),id(12)));}
 void assertTasks(int n,Set<String> actors){
  var ts=tasks();assertEquals(actors.size(),ts.size());
  assertEquals(actors,new HashSet<>(ts.stream().map(Task::getAssignee).toList()));
  assertTrue(ts.stream().allMatch(t->node(n).equals(t.getTaskDefinitionKey())));
  assertEquals(ts.size(),new HashSet<>(ids(ts)).size());
 }
 void assertFreshFirstCounters(){
  assertTasks(2,Set.of(id(8),id(9)));
  var runtime=engine.getRuntimeService();
  for(var task:tasks()){
   assertEquals(2,((Number)runtime.getVariable(task.getExecutionId(),"nrOfInstances")).intValue());
   assertEquals(2,((Number)runtime.getVariable(task.getExecutionId(),"nrOfActiveInstances")).intValue());
   assertEquals(0,((Number)runtime.getVariable(task.getExecutionId(),"nrOfCompletedInstances")).intValue());
   assertEquals(task.getAssignee(),runtime.getVariable(task.getExecutionId(),"approver"));
  }
 }
 void returnToFirst(){
  new TransactionTemplate(tm).executeWithoutResult(tx->engine.getRuntimeService()
   .createChangeActivityStateBuilder().processInstanceId(process)
   .moveActivityIdTo(node(3),node(2)).changeState());
 }
 @ParameterizedTest @ValueSource(strings={"all","any"})
 void returnFromSecondMiRecreatesVisitedRosterAndResetsCounters(String mode) throws Exception {
  start(mode);List<String> originalFirst=ids(tasks());reachSecond();List<String> originalSecond=ids(tasks());
  if(mode.equals("all")){complete(id(10));assertEquals(2,tasks().size());}
  returnToFirst();assertFreshFirstCounters();
  Set<String> obsolete=new HashSet<>(originalFirst);obsolete.addAll(originalSecond);
  assertTrue(tasks().stream().noneMatch(t->obsolete.contains(t.getId())));
  for(String old:originalSecond){
   assertNull(engine.getTaskService().createTaskQuery().taskId(old).singleResult());
   assertThrows(FlowableObjectNotFoundException.class,()->engine.getTaskService().complete(old));
  }
  complete(id(8));assertTasks(2,Set.of(id(9)));
  assertEquals(1,((Number)engine.getRuntimeService().getVariable(assigned(id(9)).getExecutionId(),"nrOfCompletedInstances")).intValue());
  complete(id(9));assertTasks(3,Set.of(id(10),id(11),id(12)));
  assertTrue(tasks().stream().noneMatch(t->originalSecond.contains(t.getId())));
  assertEquals(4,engine.getHistoryService().createHistoricTaskInstanceQuery().processInstanceId(process)
   .taskDefinitionKey(node(2)).finished().count());
  complete(id(10));
  if(mode.equals("all")){assertTasks(3,Set.of(id(11),id(12)));complete(id(11));complete(id(12));}
  assertEquals(0,tasks().size());
  assertEquals(0,engine.getRuntimeService().createProcessInstanceQuery().processInstanceId(process).count());
 }
 @Test void returnToCurrentPartiallyCompletedNodeStartsANewActivation() throws Exception {
  start("all");List<String> old=ids(tasks());complete(id(8));assertTasks(2,Set.of(id(9)));
  new TransactionTemplate(tm).executeWithoutResult(tx->engine.getRuntimeService()
   .createChangeActivityStateBuilder().processInstanceId(process)
   .moveActivityIdTo(node(2),node(2)).changeState());
  assertFreshFirstCounters();assertTrue(tasks().stream().noneMatch(t->old.contains(t.getId())));
  complete(id(8));assertTasks(2,Set.of(id(9)));complete(id(9));assertTasks(3,Set.of(id(10),id(11),id(12)));
 }
 @Test void rollbackAfterMovementRestoresExactPriorMiTasks() throws Exception {
  start("all");reachSecond();complete(id(10));List<String> before=ids(tasks());
  long historicalBefore=engine.getHistoryService().createHistoricTaskInstanceQuery().processInstanceId(process).count();
  assertThrows(InjectedFailure.class,()->new TransactionTemplate(tm).executeWithoutResult(tx->{
   engine.getRuntimeService().createChangeActivityStateBuilder().processInstanceId(process)
    .moveActivityIdTo(node(3),node(2)).changeState();
   assertFreshFirstCounters();throw new InjectedFailure();
  }));
  assertEquals(before,ids(tasks()));assertTasks(3,Set.of(id(11),id(12)));
  assertEquals(historicalBefore,engine.getHistoryService().createHistoricTaskInstanceQuery().processInstanceId(process).count());
  complete(id(11));assertTasks(3,Set.of(id(12)));complete(id(12));assertEquals(0,tasks().size());
 }
 @Test void withdrawalRollsBackThenRemovesAllRuntimeTasksButRetainsHistory() throws Exception {
  start("all");reachSecond();complete(id(10));List<String> before=ids(tasks());
  assertThrows(InjectedFailure.class,()->new TransactionTemplate(tm).executeWithoutResult(tx->{
   engine.getRuntimeService().deleteProcessInstance(process,"root-fixture-withdraw");
   assertEquals(0,tasks().size());throw new InjectedFailure();
  }));
  assertEquals(before,ids(tasks()));
  new TransactionTemplate(tm).executeWithoutResult(tx->engine.getRuntimeService().deleteProcessInstance(process,"root-fixture-withdraw"));
  assertEquals(0,tasks().size());
  assertEquals(0,engine.getRuntimeService().createProcessInstanceQuery().processInstanceId(process).count());
  var historic=engine.getHistoryService().createHistoricProcessInstanceQuery().processInstanceId(process).singleResult();
  assertNotNull(historic);assertNotNull(historic.getEndTime());assertEquals("root-fixture-withdraw",historic.getDeleteReason());
  assertEquals(5,engine.getHistoryService().createHistoricTaskInstanceQuery().processInstanceId(process).count());
 }
 static final class InjectedFailure extends RuntimeException{}
}
