// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.25.9
// source: weaveos/workflow/v1/execution.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecutionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CommandEnvelope []byte                 `protobuf:"bytes,1,opt,name=command_envelope,json=commandEnvelope,proto3" json:"command_envelope,omitempty"`
	Payload         []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExecutionRequest) Reset() {
	*x = ExecutionRequest{}
	mi := &file_weaveos_workflow_v1_execution_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionRequest) ProtoMessage() {}

func (x *ExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_weaveos_workflow_v1_execution_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionRequest.ProtoReflect.Descriptor instead.
func (*ExecutionRequest) Descriptor() ([]byte, []int) {
	return file_weaveos_workflow_v1_execution_proto_rawDescGZIP(), []int{0}
}

func (x *ExecutionRequest) GetCommandEnvelope() []byte {
	if x != nil {
		return x.CommandEnvelope
	}
	return nil
}

func (x *ExecutionRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ExecutionReceipt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	CommandHash   []byte                 `protobuf:"bytes,2,opt,name=command_hash,json=commandHash,proto3" json:"command_hash,omitempty"`
	Outcome       string                 `protobuf:"bytes,3,opt,name=outcome,proto3" json:"outcome,omitempty"`
	Sequence      uint64                 `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
	ProofId       string                 `protobuf:"bytes,5,opt,name=proof_id,json=proofId,proto3" json:"proof_id,omitempty"`
	ResultHash    []byte                 `protobuf:"bytes,6,opt,name=result_hash,json=resultHash,proto3" json:"result_hash,omitempty"`
	ResultBytes   []byte                 `protobuf:"bytes,7,opt,name=result_bytes,json=resultBytes,proto3" json:"result_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionReceipt) Reset() {
	*x = ExecutionReceipt{}
	mi := &file_weaveos_workflow_v1_execution_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionReceipt) ProtoMessage() {}

func (x *ExecutionReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_weaveos_workflow_v1_execution_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionReceipt.ProtoReflect.Descriptor instead.
func (*ExecutionReceipt) Descriptor() ([]byte, []int) {
	return file_weaveos_workflow_v1_execution_proto_rawDescGZIP(), []int{1}
}

func (x *ExecutionReceipt) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *ExecutionReceipt) GetCommandHash() []byte {
	if x != nil {
		return x.CommandHash
	}
	return nil
}

func (x *ExecutionReceipt) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *ExecutionReceipt) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *ExecutionReceipt) GetProofId() string {
	if x != nil {
		return x.ProofId
	}
	return ""
}

func (x *ExecutionReceipt) GetResultHash() []byte {
	if x != nil {
		return x.ResultHash
	}
	return nil
}

func (x *ExecutionReceipt) GetResultBytes() []byte {
	if x != nil {
		return x.ResultBytes
	}
	return nil
}

type ExecutionLookupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	CommandHash   []byte                 `protobuf:"bytes,2,opt,name=command_hash,json=commandHash,proto3" json:"command_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionLookupRequest) Reset() {
	*x = ExecutionLookupRequest{}
	mi := &file_weaveos_workflow_v1_execution_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionLookupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionLookupRequest) ProtoMessage() {}

func (x *ExecutionLookupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_weaveos_workflow_v1_execution_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionLookupRequest.ProtoReflect.Descriptor instead.
func (*ExecutionLookupRequest) Descriptor() ([]byte, []int) {
	return file_weaveos_workflow_v1_execution_proto_rawDescGZIP(), []int{2}
}

func (x *ExecutionLookupRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *ExecutionLookupRequest) GetCommandHash() []byte {
	if x != nil {
		return x.CommandHash
	}
	return nil
}

type ExecutionLookupResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*ExecutionLookupResponse_Confirmed
	//	*ExecutionLookupResponse_NotObserved
	Result        isExecutionLookupResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionLookupResponse) Reset() {
	*x = ExecutionLookupResponse{}
	mi := &file_weaveos_workflow_v1_execution_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionLookupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionLookupResponse) ProtoMessage() {}

func (x *ExecutionLookupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_weaveos_workflow_v1_execution_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionLookupResponse.ProtoReflect.Descriptor instead.
func (*ExecutionLookupResponse) Descriptor() ([]byte, []int) {
	return file_weaveos_workflow_v1_execution_proto_rawDescGZIP(), []int{3}
}

func (x *ExecutionLookupResponse) GetResult() isExecutionLookupResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ExecutionLookupResponse) GetConfirmed() *ExecutionReceipt {
	if x != nil {
		if x, ok := x.Result.(*ExecutionLookupResponse_Confirmed); ok {
			return x.Confirmed
		}
	}
	return nil
}

func (x *ExecutionLookupResponse) GetNotObserved() *NotObserved {
	if x != nil {
		if x, ok := x.Result.(*ExecutionLookupResponse_NotObserved); ok {
			return x.NotObserved
		}
	}
	return nil
}

type isExecutionLookupResponse_Result interface {
	isExecutionLookupResponse_Result()
}

type ExecutionLookupResponse_Confirmed struct {
	Confirmed *ExecutionReceipt `protobuf:"bytes,1,opt,name=confirmed,proto3,oneof"`
}

type ExecutionLookupResponse_NotObserved struct {
	NotObserved *NotObserved `protobuf:"bytes,2,opt,name=not_observed,json=notObserved,proto3,oneof"`
}

func (*ExecutionLookupResponse_Confirmed) isExecutionLookupResponse_Result() {}

func (*ExecutionLookupResponse_NotObserved) isExecutionLookupResponse_Result() {}

var File_weaveos_workflow_v1_execution_proto protoreflect.FileDescriptor

const file_weaveos_workflow_v1_execution_proto_rawDesc = "" +
	"\n" +
	"#weaveos/workflow/v1/execution.proto\x12\x13weaveos.workflow.v1\x1a$weaveos/workflow/v1/deployment.proto\"W\n" +
	"\x10ExecutionRequest\x12)\n" +
	"\x10command_envelope\x18\x01 \x01(\fR\x0fcommandEnvelope\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"\xe9\x01\n" +
	"\x10ExecutionReceipt\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12!\n" +
	"\fcommand_hash\x18\x02 \x01(\fR\vcommandHash\x12\x18\n" +
	"\aoutcome\x18\x03 \x01(\tR\aoutcome\x12\x1a\n" +
	"\bsequence\x18\x04 \x01(\x04R\bsequence\x12\x19\n" +
	"\bproof_id\x18\x05 \x01(\tR\aproofId\x12\x1f\n" +
	"\vresult_hash\x18\x06 \x01(\fR\n" +
	"resultHash\x12!\n" +
	"\fresult_bytes\x18\a \x01(\fR\vresultBytes\"Z\n" +
	"\x16ExecutionLookupRequest\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12!\n" +
	"\fcommand_hash\x18\x02 \x01(\fR\vcommandHash\"\xb1\x01\n" +
	"\x17ExecutionLookupResponse\x12E\n" +
	"\tconfirmed\x18\x01 \x01(\v2%.weaveos.workflow.v1.ExecutionReceiptH\x00R\tconfirmed\x12E\n" +
	"\fnot_observed\x18\x02 \x01(\v2 .weaveos.workflow.v1.NotObservedH\x00R\vnotObservedB\b\n" +
	"\x06result2\xb3\x02\n" +
	"\x10ExecutionService\x12W\n" +
	"\aExecute\x12%.weaveos.workflow.v1.ExecutionRequest\x1a%.weaveos.workflow.v1.ExecutionReceipt\x12c\n" +
	"\x06Lookup\x12+.weaveos.workflow.v1.ExecutionLookupRequest\x1a,.weaveos.workflow.v1.ExecutionLookupResponse\x12a\n" +
	"\x11EstablishNoEffect\x12%.weaveos.workflow.v1.ExecutionRequest\x1a%.weaveos.workflow.v1.ExecutionReceiptB\\\n" +
	"\x17org.weaveos.workflow.v1P\x01Z?github.com/Hubujiu/WeaveOS/services/bff/internal/workflowrpc/pbb\x06proto3"

var (
	file_weaveos_workflow_v1_execution_proto_rawDescOnce sync.Once
	file_weaveos_workflow_v1_execution_proto_rawDescData []byte
)

func file_weaveos_workflow_v1_execution_proto_rawDescGZIP() []byte {
	file_weaveos_workflow_v1_execution_proto_rawDescOnce.Do(func() {
		file_weaveos_workflow_v1_execution_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_weaveos_workflow_v1_execution_proto_rawDesc), len(file_weaveos_workflow_v1_execution_proto_rawDesc)))
	})
	return file_weaveos_workflow_v1_execution_proto_rawDescData
}

var file_weaveos_workflow_v1_execution_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_weaveos_workflow_v1_execution_proto_goTypes = []any{
	(*ExecutionRequest)(nil),        // 0: weaveos.workflow.v1.ExecutionRequest
	(*ExecutionReceipt)(nil),        // 1: weaveos.workflow.v1.ExecutionReceipt
	(*ExecutionLookupRequest)(nil),  // 2: weaveos.workflow.v1.ExecutionLookupRequest
	(*ExecutionLookupResponse)(nil), // 3: weaveos.workflow.v1.ExecutionLookupResponse
	(*NotObserved)(nil),             // 4: weaveos.workflow.v1.NotObserved
}
var file_weaveos_workflow_v1_execution_proto_depIdxs = []int32{
	1, // 0: weaveos.workflow.v1.ExecutionLookupResponse.confirmed:type_name -> weaveos.workflow.v1.ExecutionReceipt
	4, // 1: weaveos.workflow.v1.ExecutionLookupResponse.not_observed:type_name -> weaveos.workflow.v1.NotObserved
	0, // 2: weaveos.workflow.v1.ExecutionService.Execute:input_type -> weaveos.workflow.v1.ExecutionRequest
	2, // 3: weaveos.workflow.v1.ExecutionService.Lookup:input_type -> weaveos.workflow.v1.ExecutionLookupRequest
	0, // 4: weaveos.workflow.v1.ExecutionService.EstablishNoEffect:input_type -> weaveos.workflow.v1.ExecutionRequest
	1, // 5: weaveos.workflow.v1.ExecutionService.Execute:output_type -> weaveos.workflow.v1.ExecutionReceipt
	3, // 6: weaveos.workflow.v1.ExecutionService.Lookup:output_type -> weaveos.workflow.v1.ExecutionLookupResponse
	1, // 7: weaveos.workflow.v1.ExecutionService.EstablishNoEffect:output_type -> weaveos.workflow.v1.ExecutionReceipt
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_weaveos_workflow_v1_execution_proto_init() }
func file_weaveos_workflow_v1_execution_proto_init() {
	if File_weaveos_workflow_v1_execution_proto != nil {
		return
	}
	file_weaveos_workflow_v1_deployment_proto_init()
	file_weaveos_workflow_v1_execution_proto_msgTypes[3].OneofWrappers = []any{
		(*ExecutionLookupResponse_Confirmed)(nil),
		(*ExecutionLookupResponse_NotObserved)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_weaveos_workflow_v1_execution_proto_rawDesc), len(file_weaveos_workflow_v1_execution_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_weaveos_workflow_v1_execution_proto_goTypes,
		DependencyIndexes: file_weaveos_workflow_v1_execution_proto_depIdxs,
		MessageInfos:      file_weaveos_workflow_v1_execution_proto_msgTypes,
	}.Build()
	File_weaveos_workflow_v1_execution_proto = out.File
	file_weaveos_workflow_v1_execution_proto_goTypes = nil
	file_weaveos_workflow_v1_execution_proto_depIdxs = nil
}
