// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.25.9
// source: weaveos/workflow/v1/deployment.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeployRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	FlowId        string                 `protobuf:"bytes,2,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	VersionId     string                 `protobuf:"bytes,3,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	Version       uint64                 `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	BpmnXml       []byte                 `protobuf:"bytes,5,opt,name=bpmn_xml,json=bpmnXml,proto3" json:"bpmn_xml,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployRequest) Reset() {
	*x = DeployRequest{}
	mi := &file_weaveos_workflow_v1_deployment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployRequest) ProtoMessage() {}

func (x *DeployRequest) ProtoReflect() protoreflect.Message {
	mi := &file_weaveos_workflow_v1_deployment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployRequest.ProtoReflect.Descriptor instead.
func (*DeployRequest) Descriptor() ([]byte, []int) {
	return file_weaveos_workflow_v1_deployment_proto_rawDescGZIP(), []int{0}
}

func (x *DeployRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *DeployRequest) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

func (x *DeployRequest) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

func (x *DeployRequest) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *DeployRequest) GetBpmnXml() []byte {
	if x != nil {
		return x.BpmnXml
	}
	return nil
}

type DeploymentReceipt struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AppId               string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	FlowId              string                 `protobuf:"bytes,2,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	VersionId           string                 `protobuf:"bytes,3,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	Version             uint64                 `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	BpmnSha256          string                 `protobuf:"bytes,5,opt,name=bpmn_sha256,json=bpmnSha256,proto3" json:"bpmn_sha256,omitempty"`
	EngineDeploymentId  string                 `protobuf:"bytes,6,opt,name=engine_deployment_id,json=engineDeploymentId,proto3" json:"engine_deployment_id,omitempty"`
	ProcessDefinitionId string                 `protobuf:"bytes,7,opt,name=process_definition_id,json=processDefinitionId,proto3" json:"process_definition_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DeploymentReceipt) Reset() {
	*x = DeploymentReceipt{}
	mi := &file_weaveos_workflow_v1_deployment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentReceipt) ProtoMessage() {}

func (x *DeploymentReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_weaveos_workflow_v1_deployment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentReceipt.ProtoReflect.Descriptor instead.
func (*DeploymentReceipt) Descriptor() ([]byte, []int) {
	return file_weaveos_workflow_v1_deployment_proto_rawDescGZIP(), []int{1}
}

func (x *DeploymentReceipt) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *DeploymentReceipt) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

func (x *DeploymentReceipt) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

func (x *DeploymentReceipt) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *DeploymentReceipt) GetBpmnSha256() string {
	if x != nil {
		return x.BpmnSha256
	}
	return ""
}

func (x *DeploymentReceipt) GetEngineDeploymentId() string {
	if x != nil {
		return x.EngineDeploymentId
	}
	return ""
}

func (x *DeploymentReceipt) GetProcessDefinitionId() string {
	if x != nil {
		return x.ProcessDefinitionId
	}
	return ""
}

type LookupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	FlowId        string                 `protobuf:"bytes,2,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	VersionId     string                 `protobuf:"bytes,3,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	Version       uint64                 `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	BpmnSha256    string                 `protobuf:"bytes,5,opt,name=bpmn_sha256,json=bpmnSha256,proto3" json:"bpmn_sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupRequest) Reset() {
	*x = LookupRequest{}
	mi := &file_weaveos_workflow_v1_deployment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupRequest) ProtoMessage() {}

func (x *LookupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_weaveos_workflow_v1_deployment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupRequest.ProtoReflect.Descriptor instead.
func (*LookupRequest) Descriptor() ([]byte, []int) {
	return file_weaveos_workflow_v1_deployment_proto_rawDescGZIP(), []int{2}
}

func (x *LookupRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *LookupRequest) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

func (x *LookupRequest) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

func (x *LookupRequest) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *LookupRequest) GetBpmnSha256() string {
	if x != nil {
		return x.BpmnSha256
	}
	return ""
}

// NotObserved is not a failure/no-effect verdict; a concurrent operation may commit later.
type NotObserved struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotObserved) Reset() {
	*x = NotObserved{}
	mi := &file_weaveos_workflow_v1_deployment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotObserved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotObserved) ProtoMessage() {}

func (x *NotObserved) ProtoReflect() protoreflect.Message {
	mi := &file_weaveos_workflow_v1_deployment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotObserved.ProtoReflect.Descriptor instead.
func (*NotObserved) Descriptor() ([]byte, []int) {
	return file_weaveos_workflow_v1_deployment_proto_rawDescGZIP(), []int{3}
}

type LookupResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*LookupResponse_Confirmed
	//	*LookupResponse_NotObserved
	Result        isLookupResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupResponse) Reset() {
	*x = LookupResponse{}
	mi := &file_weaveos_workflow_v1_deployment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupResponse) ProtoMessage() {}

func (x *LookupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_weaveos_workflow_v1_deployment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupResponse.ProtoReflect.Descriptor instead.
func (*LookupResponse) Descriptor() ([]byte, []int) {
	return file_weaveos_workflow_v1_deployment_proto_rawDescGZIP(), []int{4}
}

func (x *LookupResponse) GetResult() isLookupResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *LookupResponse) GetConfirmed() *DeploymentReceipt {
	if x != nil {
		if x, ok := x.Result.(*LookupResponse_Confirmed); ok {
			return x.Confirmed
		}
	}
	return nil
}

func (x *LookupResponse) GetNotObserved() *NotObserved {
	if x != nil {
		if x, ok := x.Result.(*LookupResponse_NotObserved); ok {
			return x.NotObserved
		}
	}
	return nil
}

type isLookupResponse_Result interface {
	isLookupResponse_Result()
}

type LookupResponse_Confirmed struct {
	Confirmed *DeploymentReceipt `protobuf:"bytes,1,opt,name=confirmed,proto3,oneof"`
}

type LookupResponse_NotObserved struct {
	NotObserved *NotObserved `protobuf:"bytes,2,opt,name=not_observed,json=notObserved,proto3,oneof"`
}

func (*LookupResponse_Confirmed) isLookupResponse_Result() {}

func (*LookupResponse_NotObserved) isLookupResponse_Result() {}

var File_weaveos_workflow_v1_deployment_proto protoreflect.FileDescriptor

const file_weaveos_workflow_v1_deployment_proto_rawDesc = "" +
	"\n" +
	"$weaveos/workflow/v1/deployment.proto\x12\x13weaveos.workflow.v1\"\x93\x01\n" +
	"\rDeployRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x17\n" +
	"\aflow_id\x18\x02 \x01(\tR\x06flowId\x12\x1d\n" +
	"\n" +
	"version_id\x18\x03 \x01(\tR\tversionId\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x04R\aversion\x12\x19\n" +
	"\bbpmn_xml\x18\x05 \x01(\fR\abpmnXml\"\x83\x02\n" +
	"\x11DeploymentReceipt\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x17\n" +
	"\aflow_id\x18\x02 \x01(\tR\x06flowId\x12\x1d\n" +
	"\n" +
	"version_id\x18\x03 \x01(\tR\tversionId\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x04R\aversion\x12\x1f\n" +
	"\vbpmn_sha256\x18\x05 \x01(\tR\n" +
	"bpmnSha256\x120\n" +
	"\x14engine_deployment_id\x18\x06 \x01(\tR\x12engineDeploymentId\x122\n" +
	"\x15process_definition_id\x18\a \x01(\tR\x13processDefinitionId\"\x99\x01\n" +
	"\rLookupRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x17\n" +
	"\aflow_id\x18\x02 \x01(\tR\x06flowId\x12\x1d\n" +
	"\n" +
	"version_id\x18\x03 \x01(\tR\tversionId\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x04R\aversion\x12\x1f\n" +
	"\vbpmn_sha256\x18\x05 \x01(\tR\n" +
	"bpmnSha256\"\r\n" +
	"\vNotObserved\"\xa9\x01\n" +
	"\x0eLookupResponse\x12F\n" +
	"\tconfirmed\x18\x01 \x01(\v2&.weaveos.workflow.v1.DeploymentReceiptH\x00R\tconfirmed\x12E\n" +
	"\fnot_observed\x18\x02 \x01(\v2 .weaveos.workflow.v1.NotObservedH\x00R\vnotObservedB\b\n" +
	"\x06result2\xbc\x01\n" +
	"\x11DeploymentService\x12T\n" +
	"\x06Deploy\x12\".weaveos.workflow.v1.DeployRequest\x1a&.weaveos.workflow.v1.DeploymentReceipt\x12Q\n" +
	"\x06Lookup\x12\".weaveos.workflow.v1.LookupRequest\x1a#.weaveos.workflow.v1.LookupResponseB\\\n" +
	"\x17org.weaveos.workflow.v1P\x01Z?github.com/Hubujiu/WeaveOS/services/bff/internal/workflowrpc/pbb\x06proto3"

var (
	file_weaveos_workflow_v1_deployment_proto_rawDescOnce sync.Once
	file_weaveos_workflow_v1_deployment_proto_rawDescData []byte
)

func file_weaveos_workflow_v1_deployment_proto_rawDescGZIP() []byte {
	file_weaveos_workflow_v1_deployment_proto_rawDescOnce.Do(func() {
		file_weaveos_workflow_v1_deployment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_weaveos_workflow_v1_deployment_proto_rawDesc), len(file_weaveos_workflow_v1_deployment_proto_rawDesc)))
	})
	return file_weaveos_workflow_v1_deployment_proto_rawDescData
}

var file_weaveos_workflow_v1_deployment_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_weaveos_workflow_v1_deployment_proto_goTypes = []any{
	(*DeployRequest)(nil),     // 0: weaveos.workflow.v1.DeployRequest
	(*DeploymentReceipt)(nil), // 1: weaveos.workflow.v1.DeploymentReceipt
	(*LookupRequest)(nil),     // 2: weaveos.workflow.v1.LookupRequest
	(*NotObserved)(nil),       // 3: weaveos.workflow.v1.NotObserved
	(*LookupResponse)(nil),    // 4: weaveos.workflow.v1.LookupResponse
}
var file_weaveos_workflow_v1_deployment_proto_depIdxs = []int32{
	1, // 0: weaveos.workflow.v1.LookupResponse.confirmed:type_name -> weaveos.workflow.v1.DeploymentReceipt
	3, // 1: weaveos.workflow.v1.LookupResponse.not_observed:type_name -> weaveos.workflow.v1.NotObserved
	0, // 2: weaveos.workflow.v1.DeploymentService.Deploy:input_type -> weaveos.workflow.v1.DeployRequest
	2, // 3: weaveos.workflow.v1.DeploymentService.Lookup:input_type -> weaveos.workflow.v1.LookupRequest
	1, // 4: weaveos.workflow.v1.DeploymentService.Deploy:output_type -> weaveos.workflow.v1.DeploymentReceipt
	4, // 5: weaveos.workflow.v1.DeploymentService.Lookup:output_type -> weaveos.workflow.v1.LookupResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_weaveos_workflow_v1_deployment_proto_init() }
func file_weaveos_workflow_v1_deployment_proto_init() {
	if File_weaveos_workflow_v1_deployment_proto != nil {
		return
	}
	file_weaveos_workflow_v1_deployment_proto_msgTypes[4].OneofWrappers = []any{
		(*LookupResponse_Confirmed)(nil),
		(*LookupResponse_NotObserved)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_weaveos_workflow_v1_deployment_proto_rawDesc), len(file_weaveos_workflow_v1_deployment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_weaveos_workflow_v1_deployment_proto_goTypes,
		DependencyIndexes: file_weaveos_workflow_v1_deployment_proto_depIdxs,
		MessageInfos:      file_weaveos_workflow_v1_deployment_proto_msgTypes,
	}.Build()
	File_weaveos_workflow_v1_deployment_proto = out.File
	file_weaveos_workflow_v1_deployment_proto_goTypes = nil
	file_weaveos_workflow_v1_deployment_proto_depIdxs = nil
}
