import {test,expect,type Page,type BrowserContext,type Locator,type APIResponse} from '@playwright/test';
import {readFileSync,mkdirSync} from 'node:fs';
import {rename} from 'node:fs/promises';
import {resolve} from 'node:path';
import type {TablePreset} from '../../apps/web/src/TablePresetState';
import type {Member,Definition} from '../../apps/web/src/workspace-types';
import type {MembersQueryPage} from '../../apps/web/src/query-contracts';

// PRD / ADR008 A1–A7, reread at frozen revisions 02:58 UTC. Real APIs only;
// no request mocks, no credential-bearing browser trace or login video.
test.use({trace:'off',screenshot:'off',video:'off'});
const base=process.env.WEAVEOS_WEB_URL!;
if(!base?.startsWith('https://')||!['localhost','127.0.0.1'].includes(new URL(base).hostname))throw Error('isolated HTTPS required');
const fixture=JSON.parse(readFileSync(process.env.WEAVEOS_ACCEPTANCE_FIXTURES!,'utf8')) as {admin:{account:string;password:string};user:{account:string;password:string};userId:string};
const evidence=resolve('docs/evidence/V010-020/filter-manager/real');mkdirSync(evidence,{recursive:true});
const created:string[]=[];let counter=0;const stamp=Date.now();
const name=(label:string)=>label+'-'+test.info().project.name+'-'+stamp+'-'+(++counter);
async function login(context:BrowserContext,credentials=fixture.admin){const res=await context.request.post(base+'/api/v1/sessions',{headers:{Origin:base},data:credentials});expect(res.status(),'synthetic login').toBe(201);}
async function request(page:Page,path:string,method='GET',data?:object):Promise<APIResponse>{const csrf=(await page.context().cookies(base)).find(c=>c.name==='__Host-csrf');return page.request.fetch(base+'/api/v1/'+path,{method,headers:{Origin:base,...(csrf?{'X-CSRF-Token':csrf.value}:{})},...(data?{data}:{})});}
async function api<T>(page:Page,path:string,method='GET',data?:object):Promise<T>{const res=await request(page,path,method,data);expect(res.ok(),method+' '+path.split('?')[0]+' status '+res.status()).toBe(true);if(res.status()===204)return undefined as T;const body=await res.json();expect(body.code).toBe('OK');return body.data as T;}
async function enter(page:Page){await login(page.context());page.on('dialog',d=>void d.accept());await page.goto('/app/admin');await expect(page.locator('.member-table table')).toHaveAttribute('aria-busy','false');await expect(page.locator('.member-table tbody tr[data-row-id]').first()).toBeVisible();}
async function manager(page:Page){await page.getByRole('button',{name:/^自定义筛选/}).click();const d=page.getByRole('dialog',{name:'管理自定义筛选',exact:true});await expect(d).toBeVisible();return d;}
async function newEditor(page:Page,panel:Locator){await panel.getByRole('button',{name:'新增筛选',exact:true}).click();const d=page.getByRole('dialog',{name:'新增自定义筛选',exact:true});await expect(d).toBeVisible();return d;}
async function create(page:Page,label:string,hidden:string[]=[],filter:unknown=null,view='members'){const p=await api<TablePreset>(page,'personnel/table-presets','POST',{view,name:name(label),hiddenColumnIds:hidden,filter,schemaVersion:1});created.push(p.id);return p;}
async function save(page:Page,d:Locator){const response=page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname.endsWith('/table-presets'));await d.getByRole('button',{name:'确定',exact:true}).click();const r=await response;expect(r.status()).toBe(201);const p=(await r.json()).data as TablePreset;created.push(p.id);return p;}
async function close(panel:Locator){await panel.getByRole('button',{name:'关闭筛选管理',exact:true}).click();await expect(panel).toBeHidden();}
async function settle(page:Page){await page.evaluate(()=>document.fonts.ready);await page.waitForFunction(()=>!document.documentElement.classList.contains('q36-filter-transition-active'));await page.evaluate(()=>Promise.allSettled(document.getAnimations().map(a=>a.finished)));}
async function shot(page:Page,label:string){await settle(page);await page.screenshot({path:resolve(evidence,test.info().project.name+'-'+label+'.png'),fullPage:true});}
async function apply(panel:Locator,p:TablePreset){await panel.getByRole('button',{name:'应用'+p.name,exact:true}).click();await expect(panel.getByText('已应用',{exact:true})).toHaveCount(1);}
async function cancel(page:Page,panel:Locator){await panel.getByRole('button',{name:'取消应用',exact:true}).click();const c=page.getByRole('dialog',{name:'取消当前筛选',exact:true});await expect(c).toBeVisible();await c.getByRole('button',{name:'确认取消',exact:true}).click();await expect(panel.getByText('已应用',{exact:true})).toHaveCount(0);}
test.afterEach(async({page})=>{for(const id of created.splice(0)){const r=await request(page,'personnel/table-presets/'+id);if(r.status()===404)continue;expect(r.ok()).toBe(true);const p=(await r.json()).data as TablePreset;expect((await request(page,'personnel/table-presets/'+id+'?version='+p.version,'DELETE')).status()).toBe(204);}});

test('real centered empty manager, finite AND OR typed save-only, visibility and fresh-login persistence',async({page,browser})=>{
 await enter(page);const queries:Record<string,unknown>[]=[];page.on('request',r=>{if(r.url().endsWith('/personnel/members/search'))queries.push(r.postDataJSON());});const panel=await manager(page);await expect(panel).toContainText('暂无自定义筛选');const b=(await panel.boundingBox())!;expect(b.width).toBe(440);expect(b.x+b.width/2).toBeCloseTo(720,0);expect(b.y+b.height/2).toBeCloseTo(500,0);await shot(page,'manager-empty');
 const d=await newEditor(page,panel);await d.getByLabel('自定义筛选名称',{exact:true}).fill('  '+name('成员方案')+'  ');await shot(page,'editor-empty');await d.getByRole('button',{name:'或条件',exact:true}).click();await d.getByLabel('条件 1.1 值',{exact:true}).fill(fixture.admin.account);
 await d.getByRole('button',{name:'组 1 且条件',exact:true}).click();await d.getByLabel('条件 1.2 字段',{exact:true}).selectOption('status');await d.getByLabel('条件 1.2 值',{exact:true}).selectOption('active');await d.getByRole('button',{name:'或条件',exact:true}).click();await d.getByLabel('条件 2.1 值',{exact:true}).fill(fixture.user.account);
 await d.getByRole('button',{name:'隐藏部门',exact:true}).click();await d.getByLabel('隐藏字段搜索',{exact:true}).fill('部门');await d.getByLabel('显示字段搜索',{exact:true}).fill('身份');await shot(page,'editor-and-or-dual-search');await expect(d.getByRole('button',{name:'隐藏成员',exact:true})).toHaveCount(0);await expect(d.getByRole('button',{name:'显示部门',exact:true})).toBeVisible();
 const p=await save(page,d);expect(queries).toHaveLength(0);expect(p.name).toBe(p.name.trim());expect(p.filter).toEqual({operator:'or',children:[{operator:'and',children:[{field:'account',operator:'eq',value:fixture.admin.account},{field:'status',operator:'eq',value:'active'}]},{operator:'and',children:[{field:'account',operator:'eq',value:fixture.user.account}]}]});expect(p.hiddenColumnIds).toEqual(['departments']);await shot(page,'manager-saved');await close(panel);await page.reload();await expect(page.getByRole('button',{name:'自定义筛选',exact:true})).toBeVisible();await expect(page.locator('.member-table thead')).toContainText('部门');
 const context=await browser.newContext({ignoreHTTPSErrors:true});try{await login(context);const other=await context.newPage();await other.goto('/app/admin');const again=await manager(other);await expect(again.getByRole('button',{name:'应用'+p.name,exact:true})).toBeVisible();await expect(again.getByText('已应用',{exact:true})).toHaveCount(0);}finally{await context.close();}
});

test('real one active snapshot, save-without-apply, first baseline across A B, widths and confirmed deletion',async({page})=>{
 await enter(page);const a=await create(page,'隐藏部门',['departments']),b=await create(page,'隐藏身份',['identities']);const headers=page.locator('.member-table thead');const before=(await headers.getByRole('columnheader').filter({hasText:'成员'}).boundingBox())!.width;let queryCount=0;page.on('request',r=>{if(r.url().endsWith('/personnel/members/search'))queryCount++;});const panel=await manager(page);await apply(panel,a);await expect(headers).not.toContainText('部门');expect(queryCount).toBe(0);await shot(page,'manager-active');
 await panel.getByRole('button',{name:'编辑'+a.name,exact:true}).click();const d=page.getByRole('dialog',{name:'编辑自定义筛选',exact:true});await d.getByRole('button',{name:'显示部门',exact:true}).click();await d.getByRole('button',{name:'确定',exact:true}).click();await expect(panel).toContainText('已修改，待应用');await expect(headers).not.toContainText('部门');expect(queryCount).toBe(0);
 await apply(panel,b);await expect(headers).toContainText('部门');await expect(headers).not.toContainText('身份');await cancel(page,panel);await expect(headers).toContainText('部门');await expect(headers).toContainText('身份');expect((await headers.getByRole('columnheader').filter({hasText:'成员'}).boundingBox())!.width).toBeCloseTo(before,0);expect(queryCount).toBe(0);
 await apply(panel,b);await panel.getByRole('button',{name:'删除'+b.name,exact:true}).click();const c=page.getByRole('dialog',{name:'删除筛选方案',exact:true});await expect(c).toContainText('取消当前应用');await shot(page,'delete-active-confirm');await c.getByRole('button',{name:'返回',exact:true}).click();await expect(headers).not.toContainText('身份');await panel.getByRole('button',{name:'删除'+b.name,exact:true}).click();await c.getByRole('button',{name:'确认删除',exact:true}).click();await expect(headers).toContainText('身份');expect((await request(page,'personnel/table-presets/'+b.id)).status()).toBe(404);await expect(panel.getByText('已应用',{exact:true})).toHaveCount(0);
});

test('real stale CAS preserves input and explicit reload; precise same-view name collision',async({page})=>{
 await enter(page);const p=await create(page,'并发方案');const panel=await manager(page);await panel.getByRole('button',{name:'编辑'+p.name,exact:true}).click();const d=page.getByRole('dialog',{name:'编辑自定义筛选',exact:true});const local=name('保留当前输入');await d.getByLabel('自定义筛选名称',{exact:true}).fill(local);await api(page,'personnel/table-presets/'+p.id,'PUT',{name:p.name,filter:null,hiddenColumnIds:['departments'],schemaVersion:1,version:p.version});await d.getByRole('button',{name:'确定',exact:true}).click();await expect(d.getByRole('alert')).toContainText('其他标签页');await expect(d.getByLabel('自定义筛选名称',{exact:true})).toHaveValue(local);await shot(page,'cas-conflict');await d.getByRole('button',{name:'重新加载最新方案',exact:true}).click();const c=page.getByRole('dialog',{name:'重新加载最新方案',exact:true});await expect(c).toBeVisible();await c.getByRole('button',{name:'返回',exact:true}).click();await expect(d.getByLabel('自定义筛选名称',{exact:true})).toHaveValue(local);await d.getByRole('button',{name:'重新加载最新方案',exact:true}).click();await c.getByRole('button',{name:'确认重新加载',exact:true}).click();await expect(d.getByLabel('自定义筛选名称',{exact:true})).toHaveValue(p.name);await expect(d.getByRole('button',{name:'显示部门',exact:true})).toBeVisible();await d.getByRole('button',{name:'取消',exact:true}).click();const fresh=await newEditor(page,panel);await fresh.getByLabel('自定义筛选名称',{exact:true}).fill(p.name);await fresh.getByRole('button',{name:'确定',exact:true}).click();await expect(fresh.getByRole('alert')).toContainText('名称已存在');await expect(fresh.getByLabel('自定义筛选名称',{exact:true})).toHaveValue(p.name);await shot(page,'name-conflict');
});

test('real quota is twenty per view, UI disables new and a deletion frees a slot',async({page})=>{
 await enter(page);const list:TablePreset[]=[];for(let i=0;i<20;i++)list.push(await create(page,'额度'+i));const panel=await manager(page);await expect(panel.locator('.preset-list li')).toHaveCount(20);await expect(panel.getByRole('button',{name:'新增筛选',exact:true})).toBeDisabled();const denied=await request(page,'personnel/table-presets','POST',{view:'members',name:name('超额'),filter:null,hiddenColumnIds:[],schemaVersion:1});expect(denied.status()).toBe(409);expect((await denied.json()).code).toBe('PERSONNEL_PRESET_LIMIT_REACHED');await panel.getByRole('button',{name:'删除'+list[0].name,exact:true}).click();await page.getByRole('dialog',{name:'删除筛选方案',exact:true}).getByRole('button',{name:'确认删除',exact:true}).click();await expect(panel.getByRole('button',{name:'新增筛选',exact:true})).toBeEnabled();await create(page,'空出的额度');const event=await create(page,'另一视图额度',[],null,'events');expect(event.view).toBe('events');
});

test('real permission and owner isolation forbid foreign GET PUT DELETE and live revoked access',async({page,browser})=>{
 await enter(page);const p=await create(page,'仅本账户');const target=await api<Member>(page,'personnel/members/'+fixture.userId);const grant=await api<Definition>(page,'personnel/identities','POST',{name:name('隔离授权'),description:'仅合成测试',templateIds:[],permissionCodes:['personnel.manage']});const q=await api<MembersQueryPage<Member>>(page,'personnel/members/search','POST',{page:1,pageSize:20});await api(page,'personnel/members/'+target.id+'/identities','PUT',{version:target.version,identityIds:[...target.identityIds,grant.id],queryVersion:q.queryVersion});const context=await browser.newContext({ignoreHTTPSErrors:true});try{
  await login(context,fixture.user);const other=await context.newPage();await other.goto('/app/admin');await expect(other.getByRole('button',{name:/^自定义筛选/})).toBeVisible();expect((await api<{items:TablePreset[]}>(other,'personnel/table-presets?view=members')).items.some(v=>v.id===p.id)).toBe(false);
  for(const method of ['GET','PUT','DELETE']){const r=await request(other,'personnel/table-presets/'+p.id+(method==='DELETE'?'?version=1':''),method,method==='PUT'?{version:1,name:p.name,filter:null,hiddenColumnIds:[],schemaVersion:1}:undefined);expect(r.status(),'foreign '+method).toBe(404);}
  const latest=await api<Member>(page,'personnel/members/'+target.id),current=await api<MembersQueryPage<Member>>(page,'personnel/members/search','POST',{page:1,pageSize:20});await api(page,'personnel/members/'+target.id+'/identities','PUT',{version:latest.version,identityIds:target.identityIds,queryVersion:current.queryVersion});expect((await request(other,'personnel/table-presets?view=members')).status()).toBe(403);
 }finally{await context.close();const latest=await api<Member>(page,'personnel/members/'+target.id);if(latest.identityIds.includes(grant.id)){const current=await api<MembersQueryPage<Member>>(page,'personnel/members/search','POST',{page:1,pageSize:20});await api(page,'personnel/members/'+target.id+'/identities','PUT',{version:latest.version,identityIds:target.identityIds,queryVersion:current.queryVersion});}}
});

test('real events hidden time still sorts server results, time comparisons NULL and narrow fixed footer',async({page})=>{
 await enter(page);await page.getByRole('tab',{name:'操作记录',exact:true}).click();await expect(page.locator('.activity-table table')).toHaveAttribute('aria-busy','false');await page.getByRole('button',{name:'排序 occurredAt',exact:true}).click();await page.getByRole('menuitem',{name:'升序',exact:true}).click();await expect(page.locator('.activity-table th[aria-sort]')).toHaveAttribute('aria-sort','ascending');const p=await create(page,'隐藏时间',['occurredAt'],null,'events');const panel=await manager(page);await apply(panel,p);await expect(page.locator('.activity-table thead')).not.toContainText('时间');await close(panel);await page.getByRole('button',{name:'刷新查询',exact:true}).click();await expect(page.locator('.activity-table table')).toHaveAttribute('aria-busy','false');const values=await page.locator('.activity-table tbody tr[data-row-id]').evaluateAll(rows=>rows.map(r=>r.textContent));expect(values.length).toBeGreaterThan(0);
 const again=await manager(page),d=await newEditor(page,again);await d.getByLabel('自定义筛选名称',{exact:true}).fill(name('时间比较'));await d.getByRole('button',{name:'或条件',exact:true}).click();await d.getByLabel('条件 1.1 字段',{exact:true}).selectOption('occurredAt');await expect(d.getByLabel('条件 1.1 字段',{exact:true})).toContainText('时间（已隐藏）');await d.getByLabel('条件 1.1 比较',{exact:true}).selectOption('gte');await d.getByLabel('条件 1.1 值类型',{exact:true}).selectOption('date');await d.getByLabel('条件 1.1 日期',{exact:true}).fill('2026-10-02');await d.getByLabel('条件 1.1 时区',{exact:true}).fill('Asia/Shanghai');await d.getByRole('button',{name:'组 1 且条件',exact:true}).click();await d.getByLabel('条件 1.2 字段',{exact:true}).selectOption('actorAccount');await d.getByLabel('条件 1.2 值类型',{exact:true}).selectOption('null');await shot(page,'events-time-null');
 await expect(d.getByLabel('条件 1.1 比较',{exact:true}).locator('option')).toHaveText(['等于','不等于','晚于','不早于','早于','不晚于']);await d.getByLabel('条件 1.1 比较',{exact:true}).click();await page.screenshot({path:resolve(evidence,test.info().project.name+'-operators-menu.png'),fullPage:true});await d.getByLabel('自定义筛选名称',{exact:true}).click();await d.getByLabel('条件 1.1 比较',{exact:true}).selectOption('gte');await page.setViewportSize({width:390,height:844});await shot(page,'editor-narrow');const box=(await d.boundingBox())!;expect(box.x).toBeGreaterThanOrEqual(12);expect(box.x+box.width).toBeLessThanOrEqual(378);await expect(d.getByRole('button',{name:'确定',exact:true})).toBeInViewport();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const stored=await save(page,d);expect(stored.filter).toEqual({operator:'and',children:[{field:'occurredAt',operator:'gte',value:{date:'2026-10-02',timeZone:'Asia/Shanghai'}},{field:'actorAccount',operator:'eq',value:null}]});
});

test('real actual formal page open close reversal and reduced motion video',async({browser})=>{
 const context=await browser.newContext({ignoreHTTPSErrors:true,viewport:{width:1440,height:1000},recordVideo:{dir:evidence,size:{width:1440,height:1000}}});await login(context);const page=await context.newPage();await page.goto('/app/admin');await expect(page.locator('.member-table table')).toHaveAttribute('aria-busy','false');await settle(page);const trigger=page.getByRole('button',{name:'自定义筛选',exact:true}),d=page.getByRole('dialog',{name:'管理自定义筛选',exact:true});await page.waitForTimeout(400);await trigger.click();await expect(d).toBeVisible();await settle(page);await page.waitForTimeout(600);
 const triggerBox=(await trigger.boundingBox())!,closeBox=(await d.getByRole('button',{name:'关闭筛选管理',exact:true}).boundingBox())!;await page.evaluate(()=>{(window as unknown as {presetTrusted:boolean[]}).presetTrusted=[];for(const el of [document.querySelector('[aria-label="关闭筛选管理"]'),document.querySelector('.q36-filter-trigger')])el?.addEventListener('click',e=>(window as unknown as {presetTrusted:boolean[]}).presetTrusted.push(e.isTrusted),{once:true});});await page.mouse.click(closeBox.x+closeBox.width/2,closeBox.y+closeBox.height/2);await page.waitForTimeout(60);await page.mouse.click(triggerBox.x+triggerBox.width/2,triggerBox.y+triggerBox.height/2);expect(await page.evaluate(()=>(window as unknown as {presetTrusted:boolean[]}).presetTrusted)).toEqual([true,true]);await expect(d).toBeVisible();await settle(page);await page.waitForTimeout(500);await page.keyboard.press('Escape');await expect(d).toBeHidden();await settle(page);await expect(trigger).toBeFocused();await expect(trigger.locator('svg')).toBeVisible();await page.waitForTimeout(500);await trigger.click();await expect(d).toBeVisible();await shot(page,'motion-reopen');await page.waitForTimeout(500);await page.keyboard.press('Escape');await expect(d).toBeHidden();await settle(page);await page.emulateMedia({reducedMotion:'reduce'});await trigger.click();await expect(d).toBeVisible();await page.keyboard.press('Escape');await expect(d).toBeHidden();await settle(page);await expect(trigger).toBeFocused();await page.waitForTimeout(500);const video=page.video();await context.close();if(!video)throw Error('formal-page video unavailable');await rename(await video.path(),resolve(evidence,test.info().project.name+'-formal-open-close-reversal-reduced.webm'));
});

test('real deleted reference fails before search and keeps the original persisted predicate',async({page})=>{
 await enter(page);const identity=await api<Definition>(page,'personnel/identities','POST',{name:name('待删除引用'),description:'仅合成测试',templateIds:[],permissionCodes:[]});const filter={operator:'and',children:[{field:'identityIds',operator:'eq',value:identity.id}]};const p=await create(page,'失效引用',[],filter);await api(page,'personnel/identities/'+identity.id+'?version='+identity.version,'DELETE');let count=0;page.on('request',r=>{if(r.url().endsWith('/personnel/members/search'))count++;});const panel=await manager(page);await panel.getByRole('button',{name:'应用'+p.name,exact:true}).click();await expect(panel.getByRole('alert')).toContainText('已失效引用');expect(count).toBe(0);await expect(panel.getByText('已应用',{exact:true})).toHaveCount(0);expect((await api<TablePreset>(page,'personnel/table-presets/'+p.id)).filter).toEqual(filter);await shot(page,'reference-conflict');
});

test('real hidden identity change still invalidates apply; successful delete and failed clear retain old snapshot',async({page})=>{
 await enter(page);const a=await create(page,'当前显隐',['identities']),b=await create(page,'待应用过滤',['departments'],{operator:'and',children:[{field:'account',operator:'eq',value:fixture.admin.account}]});const panel=await manager(page);await apply(panel,a);await expect(page.locator('.member-table thead')).not.toContainText('身份');await close(panel);const selected=page.getByLabel('选择成员：'+fixture.admin.account,{exact:true});await selected.check();
 const target=await api<Member>(page,'personnel/members/'+fixture.userId),identity=await api<Definition>(page,'personnel/identities','POST',{name:name('隐藏依赖'),description:'仅合成测试',templateIds:[],permissionCodes:[]}),query=await api<MembersQueryPage<Member>>(page,'personnel/members/search','POST',{page:1,pageSize:20});await api(page,'personnel/members/'+target.id+'/identities','PUT',{identityIds:[...target.identityIds,identity.id],version:target.version,queryVersion:query.queryVersion});
 try{const again=await manager(page);let count=0;page.on('request',r=>{if(r.url().endsWith('/personnel/members/search'))count++;});await again.getByRole('button',{name:'应用'+b.name,exact:true}).click();await expect(again.getByRole('alert')).toContainText('查询结果已变化');expect(count).toBe(1);await expect(selected).toBeChecked();await expect(page.locator('.member-table thead')).not.toContainText('身份');await expect(page.locator('.member-table thead')).toContainText('部门');await expect(again.locator('li').filter({hasText:a.name})).toContainText('已应用');
  await again.getByRole('button',{name:'删除'+a.name,exact:true}).click();await page.getByRole('dialog',{name:'删除筛选方案',exact:true}).getByRole('button',{name:'确认删除',exact:true}).click();await expect(again.getByRole('alert')).toContainText('方案已删除');await expect(again.getByRole('alert')).toContainText('查询结果已变化');expect((await request(page,'personnel/table-presets/'+a.id)).status()).toBe(404);await expect(page.locator('.member-table thead')).not.toContainText('身份');await expect(selected).toBeChecked();await shot(page,'deleted-success-query-conflict');await close(again);await page.getByRole('button',{name:'刷新查询',exact:true}).click();await expect(page.locator('.member-table table')).toHaveAttribute('aria-busy','false');await cancel(page,await manager(page));await expect(page.locator('.member-table thead')).toContainText('身份');
 }finally{const latest=await api<Member>(page,'personnel/members/'+target.id),q=await api<MembersQueryPage<Member>>(page,'personnel/members/search','POST',{page:1,pageSize:20});await api(page,'personnel/members/'+target.id+'/identities','PUT',{identityIds:target.identityIds,version:latest.version,queryVersion:q.queryVersion});}
});
