// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package authsql

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendRegistrationEvent = `-- name: AppendRegistrationEvent :exec
INSERT INTO auth.authentication_events
    (event_type, outcome, subject_user_id, client_ip, user_agent, request_id)
VALUES ('register', 'success', $1, $2, $3, $4)
`

type AppendRegistrationEventParams struct {
	SubjectUserID pgtype.UUID
	ClientIp      *netip.Addr
	UserAgent     pgtype.Text
	RequestID     string
}

func (q *Queries) AppendRegistrationEvent(ctx context.Context, arg AppendRegistrationEventParams) error {
	_, err := q.db.Exec(ctx, appendRegistrationEvent,
		arg.SubjectUserID,
		arg.ClientIp,
		arg.UserAgent,
		arg.RequestID,
	)
	return err
}

const consumeInvitation = `-- name: ConsumeInvitation :one
UPDATE auth.invitations SET used_by = $2, used_at = clock_timestamp()
WHERE id = $1 AND used_by IS NULL RETURNING id
`

type ConsumeInvitationParams struct {
	ID     pgtype.UUID
	UsedBy pgtype.UUID
}

func (q *Queries) ConsumeInvitation(ctx context.Context, arg ConsumeInvitationParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, consumeInvitation, arg.ID, arg.UsedBy)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createCredential = `-- name: CreateCredential :exec
INSERT INTO auth.password_credentials (user_id, password_hash) VALUES ($1, $2)
`

type CreateCredentialParams struct {
	UserID       pgtype.UUID
	PasswordHash string
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) error {
	_, err := q.db.Exec(ctx, createCredential, arg.UserID, arg.PasswordHash)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO auth.users (account) VALUES ($1) RETURNING id, account
`

type CreateUserRow struct {
	ID      pgtype.UUID
	Account string
}

func (q *Queries) CreateUser(ctx context.Context, account string) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, account)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.Account)
	return i, err
}

const getCurrentUser = `-- name: GetCurrentUser :one
SELECT id, account, status, is_bootstrap_admin, auth_version
FROM auth.users WHERE id = $1
`

type GetCurrentUserRow struct {
	ID               pgtype.UUID
	Account          string
	Status           string
	IsBootstrapAdmin bool
	AuthVersion      int64
}

func (q *Queries) GetCurrentUser(ctx context.Context, id pgtype.UUID) (GetCurrentUserRow, error) {
	row := q.db.QueryRow(ctx, getCurrentUser, id)
	var i GetCurrentUserRow
	err := row.Scan(
		&i.ID,
		&i.Account,
		&i.Status,
		&i.IsBootstrapAdmin,
		&i.AuthVersion,
	)
	return i, err
}

const getLoginRecord = `-- name: GetLoginRecord :one
SELECT u.id, u.account, u.status, u.is_bootstrap_admin, u.auth_version,
       c.password_hash
FROM auth.users u JOIN auth.password_credentials c ON c.user_id = u.id
WHERE u.account_key = $1
`

type GetLoginRecordRow struct {
	ID               pgtype.UUID
	Account          string
	Status           string
	IsBootstrapAdmin bool
	AuthVersion      int64
	PasswordHash     string
}

func (q *Queries) GetLoginRecord(ctx context.Context, accountKey string) (GetLoginRecordRow, error) {
	row := q.db.QueryRow(ctx, getLoginRecord, accountKey)
	var i GetLoginRecordRow
	err := row.Scan(
		&i.ID,
		&i.Account,
		&i.Status,
		&i.IsBootstrapAdmin,
		&i.AuthVersion,
		&i.PasswordHash,
	)
	return i, err
}

const lockInvitation = `-- name: LockInvitation :one
SELECT id, used_by FROM auth.invitations WHERE code_hash = $1 FOR UPDATE
`

type LockInvitationRow struct {
	ID     pgtype.UUID
	UsedBy pgtype.UUID
}

func (q *Queries) LockInvitation(ctx context.Context, codeHash []byte) (LockInvitationRow, error) {
	row := q.db.QueryRow(ctx, lockInvitation, codeHash)
	var i LockInvitationRow
	err := row.Scan(&i.ID, &i.UsedBy)
	return i, err
}
