// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package authsql

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

// 只追加的最小认证审计，不是审计中心
type AuthAuthenticationEvent struct {
	ID                 pgtype.UUID
	EventType          string
	Outcome            string
	ActorUserID        pgtype.UUID
	SubjectUserID      pgtype.UUID
	AccountFingerprint pgtype.Text
	ClientIp           *netip.Addr
	UserAgent          pgtype.Text
	// 独立非认证 UUID，不是 Cookie SID，不是 Redis 外键
	SessionRef pgtype.UUID
	ReasonCode pgtype.Text
	RequestID  string
	OccurredAt pgtype.Timestamptz
}

// 无时间过期的一次性邀请码，仅存高熵原文的摘要
type AuthInvitation struct {
	ID        pgtype.UUID
	CodeHash  []byte
	CreatedBy pgtype.UUID
	// NULL=未使用；与 used_at 同时赋值；正常应用不得清空复用
	UsedBy    pgtype.UUID
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

// 本地密码自描述哈希；不得存明文或可逆密码
type AuthPasswordCredential struct {
	UserID pgtype.UUID
	// 应用密码库验证格式；长度约束不是原始密码长度策略
	PasswordHash      string
	PasswordChangedAt pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

// v0.1.0 用户认证主档，不包含通用授权模型
type AuthUser struct {
	ID      pgtype.UUID
	Account string
	// 大小写敏感的账号唯一登录检索键；Alice 与 alice 不同
	AccountKey       string
	Status           string
	IsBootstrapAdmin bool
	// 凭据重置或状态变化时递增；Session 保存快照
	AuthVersion int64
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
