// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weaveos/workflow/v1/execution.proto

// Protobuf Java Version: 3.25.9
package org.weaveos.workflow.v1;

public final class Execution {
  private Execution() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_weaveos_workflow_v1_ExecutionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_weaveos_workflow_v1_ExecutionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_weaveos_workflow_v1_ExecutionReceipt_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_weaveos_workflow_v1_ExecutionReceipt_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_weaveos_workflow_v1_ExecutionLookupRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_weaveos_workflow_v1_ExecutionLookupRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_weaveos_workflow_v1_ExecutionLookupResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_weaveos_workflow_v1_ExecutionLookupResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#weaveos/workflow/v1/execution.proto\022\023w" +
      "eaveos.workflow.v1\032$weaveos/workflow/v1/" +
      "deployment.proto\"=\n\020ExecutionRequest\022\030\n\020" +
      "command_envelope\030\001 \001(\014\022\017\n\007payload\030\002 \001(\014\"" +
      "\234\001\n\020ExecutionReceipt\022\022\n\ncommand_id\030\001 \001(\t" +
      "\022\024\n\014command_hash\030\002 \001(\014\022\017\n\007outcome\030\003 \001(\t\022" +
      "\020\n\010sequence\030\004 \001(\004\022\020\n\010proof_id\030\005 \001(\t\022\023\n\013r" +
      "esult_hash\030\006 \001(\014\022\024\n\014result_bytes\030\007 \001(\014\"B" +
      "\n\026ExecutionLookupRequest\022\022\n\ncommand_id\030\001" +
      " \001(\t\022\024\n\014command_hash\030\002 \001(\014\"\231\001\n\027Execution" +
      "LookupResponse\022:\n\tconfirmed\030\001 \001(\0132%.weav" +
      "eos.workflow.v1.ExecutionReceiptH\000\0228\n\014no" +
      "t_observed\030\002 \001(\0132 .weaveos.workflow.v1.N" +
      "otObservedH\000B\010\n\006result2\263\002\n\020ExecutionServ" +
      "ice\022W\n\007Execute\022%.weaveos.workflow.v1.Exe" +
      "cutionRequest\032%.weaveos.workflow.v1.Exec" +
      "utionReceipt\022c\n\006Lookup\022+.weaveos.workflo" +
      "w.v1.ExecutionLookupRequest\032,.weaveos.wo" +
      "rkflow.v1.ExecutionLookupResponse\022a\n\021Est" +
      "ablishNoEffect\022%.weaveos.workflow.v1.Exe" +
      "cutionRequest\032%.weaveos.workflow.v1.Exec" +
      "utionReceiptB\\\n\027org.weaveos.workflow.v1P" +
      "\001Z?github.com/Hubujiu/WeaveOS/services/b" +
      "ff/internal/workflowrpc/pbb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.weaveos.workflow.v1.Deployment.getDescriptor(),
        });
    internal_static_weaveos_workflow_v1_ExecutionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_weaveos_workflow_v1_ExecutionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_weaveos_workflow_v1_ExecutionRequest_descriptor,
        new java.lang.String[] { "CommandEnvelope", "Payload", });
    internal_static_weaveos_workflow_v1_ExecutionReceipt_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_weaveos_workflow_v1_ExecutionReceipt_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_weaveos_workflow_v1_ExecutionReceipt_descriptor,
        new java.lang.String[] { "CommandId", "CommandHash", "Outcome", "Sequence", "ProofId", "ResultHash", "ResultBytes", });
    internal_static_weaveos_workflow_v1_ExecutionLookupRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_weaveos_workflow_v1_ExecutionLookupRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_weaveos_workflow_v1_ExecutionLookupRequest_descriptor,
        new java.lang.String[] { "CommandId", "CommandHash", });
    internal_static_weaveos_workflow_v1_ExecutionLookupResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_weaveos_workflow_v1_ExecutionLookupResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_weaveos_workflow_v1_ExecutionLookupResponse_descriptor,
        new java.lang.String[] { "Confirmed", "NotObserved", "Result", });
    org.weaveos.workflow.v1.Deployment.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
