// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weaveos/workflow/v1/execution.proto

// Protobuf Java Version: 3.25.9
package org.weaveos.workflow.v1;

/**
 * Protobuf type {@code weaveos.workflow.v1.ExecutionReceipt}
 */
public final class ExecutionReceipt extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:weaveos.workflow.v1.ExecutionReceipt)
    ExecutionReceiptOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ExecutionReceipt.newBuilder() to construct.
  private ExecutionReceipt(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ExecutionReceipt() {
    commandId_ = "";
    commandHash_ = com.google.protobuf.ByteString.EMPTY;
    outcome_ = "";
    proofId_ = "";
    resultHash_ = com.google.protobuf.ByteString.EMPTY;
    resultBytes_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ExecutionReceipt();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.weaveos.workflow.v1.Execution.internal_static_weaveos_workflow_v1_ExecutionReceipt_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.weaveos.workflow.v1.Execution.internal_static_weaveos_workflow_v1_ExecutionReceipt_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.weaveos.workflow.v1.ExecutionReceipt.class, org.weaveos.workflow.v1.ExecutionReceipt.Builder.class);
  }

  public static final int COMMAND_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object commandId_ = "";
  /**
   * <code>string command_id = 1;</code>
   * @return The commandId.
   */
  @java.lang.Override
  public java.lang.String getCommandId() {
    java.lang.Object ref = commandId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      commandId_ = s;
      return s;
    }
  }
  /**
   * <code>string command_id = 1;</code>
   * @return The bytes for commandId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCommandIdBytes() {
    java.lang.Object ref = commandId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      commandId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COMMAND_HASH_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString commandHash_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes command_hash = 2;</code>
   * @return The commandHash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getCommandHash() {
    return commandHash_;
  }

  public static final int OUTCOME_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object outcome_ = "";
  /**
   * <code>string outcome = 3;</code>
   * @return The outcome.
   */
  @java.lang.Override
  public java.lang.String getOutcome() {
    java.lang.Object ref = outcome_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      outcome_ = s;
      return s;
    }
  }
  /**
   * <code>string outcome = 3;</code>
   * @return The bytes for outcome.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOutcomeBytes() {
    java.lang.Object ref = outcome_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      outcome_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SEQUENCE_FIELD_NUMBER = 4;
  private long sequence_ = 0L;
  /**
   * <code>uint64 sequence = 4;</code>
   * @return The sequence.
   */
  @java.lang.Override
  public long getSequence() {
    return sequence_;
  }

  public static final int PROOF_ID_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object proofId_ = "";
  /**
   * <code>string proof_id = 5;</code>
   * @return The proofId.
   */
  @java.lang.Override
  public java.lang.String getProofId() {
    java.lang.Object ref = proofId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      proofId_ = s;
      return s;
    }
  }
  /**
   * <code>string proof_id = 5;</code>
   * @return The bytes for proofId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProofIdBytes() {
    java.lang.Object ref = proofId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      proofId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RESULT_HASH_FIELD_NUMBER = 6;
  private com.google.protobuf.ByteString resultHash_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes result_hash = 6;</code>
   * @return The resultHash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getResultHash() {
    return resultHash_;
  }

  public static final int RESULT_BYTES_FIELD_NUMBER = 7;
  private com.google.protobuf.ByteString resultBytes_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes result_bytes = 7;</code>
   * @return The resultBytes.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getResultBytes() {
    return resultBytes_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(commandId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, commandId_);
    }
    if (!commandHash_.isEmpty()) {
      output.writeBytes(2, commandHash_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(outcome_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, outcome_);
    }
    if (sequence_ != 0L) {
      output.writeUInt64(4, sequence_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(proofId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, proofId_);
    }
    if (!resultHash_.isEmpty()) {
      output.writeBytes(6, resultHash_);
    }
    if (!resultBytes_.isEmpty()) {
      output.writeBytes(7, resultBytes_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(commandId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, commandId_);
    }
    if (!commandHash_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, commandHash_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(outcome_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, outcome_);
    }
    if (sequence_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(4, sequence_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(proofId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, proofId_);
    }
    if (!resultHash_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(6, resultHash_);
    }
    if (!resultBytes_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(7, resultBytes_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.weaveos.workflow.v1.ExecutionReceipt)) {
      return super.equals(obj);
    }
    org.weaveos.workflow.v1.ExecutionReceipt other = (org.weaveos.workflow.v1.ExecutionReceipt) obj;

    if (!getCommandId()
        .equals(other.getCommandId())) return false;
    if (!getCommandHash()
        .equals(other.getCommandHash())) return false;
    if (!getOutcome()
        .equals(other.getOutcome())) return false;
    if (getSequence()
        != other.getSequence()) return false;
    if (!getProofId()
        .equals(other.getProofId())) return false;
    if (!getResultHash()
        .equals(other.getResultHash())) return false;
    if (!getResultBytes()
        .equals(other.getResultBytes())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + COMMAND_ID_FIELD_NUMBER;
    hash = (53 * hash) + getCommandId().hashCode();
    hash = (37 * hash) + COMMAND_HASH_FIELD_NUMBER;
    hash = (53 * hash) + getCommandHash().hashCode();
    hash = (37 * hash) + OUTCOME_FIELD_NUMBER;
    hash = (53 * hash) + getOutcome().hashCode();
    hash = (37 * hash) + SEQUENCE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSequence());
    hash = (37 * hash) + PROOF_ID_FIELD_NUMBER;
    hash = (53 * hash) + getProofId().hashCode();
    hash = (37 * hash) + RESULT_HASH_FIELD_NUMBER;
    hash = (53 * hash) + getResultHash().hashCode();
    hash = (37 * hash) + RESULT_BYTES_FIELD_NUMBER;
    hash = (53 * hash) + getResultBytes().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.weaveos.workflow.v1.ExecutionReceipt parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.weaveos.workflow.v1.ExecutionReceipt parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.weaveos.workflow.v1.ExecutionReceipt parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.weaveos.workflow.v1.ExecutionReceipt parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.weaveos.workflow.v1.ExecutionReceipt parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.weaveos.workflow.v1.ExecutionReceipt parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.weaveos.workflow.v1.ExecutionReceipt parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.weaveos.workflow.v1.ExecutionReceipt parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.weaveos.workflow.v1.ExecutionReceipt parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.weaveos.workflow.v1.ExecutionReceipt parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.weaveos.workflow.v1.ExecutionReceipt parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.weaveos.workflow.v1.ExecutionReceipt parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.weaveos.workflow.v1.ExecutionReceipt prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code weaveos.workflow.v1.ExecutionReceipt}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:weaveos.workflow.v1.ExecutionReceipt)
      org.weaveos.workflow.v1.ExecutionReceiptOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.weaveos.workflow.v1.Execution.internal_static_weaveos_workflow_v1_ExecutionReceipt_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.weaveos.workflow.v1.Execution.internal_static_weaveos_workflow_v1_ExecutionReceipt_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.weaveos.workflow.v1.ExecutionReceipt.class, org.weaveos.workflow.v1.ExecutionReceipt.Builder.class);
    }

    // Construct using org.weaveos.workflow.v1.ExecutionReceipt.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      commandId_ = "";
      commandHash_ = com.google.protobuf.ByteString.EMPTY;
      outcome_ = "";
      sequence_ = 0L;
      proofId_ = "";
      resultHash_ = com.google.protobuf.ByteString.EMPTY;
      resultBytes_ = com.google.protobuf.ByteString.EMPTY;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.weaveos.workflow.v1.Execution.internal_static_weaveos_workflow_v1_ExecutionReceipt_descriptor;
    }

    @java.lang.Override
    public org.weaveos.workflow.v1.ExecutionReceipt getDefaultInstanceForType() {
      return org.weaveos.workflow.v1.ExecutionReceipt.getDefaultInstance();
    }

    @java.lang.Override
    public org.weaveos.workflow.v1.ExecutionReceipt build() {
      org.weaveos.workflow.v1.ExecutionReceipt result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.weaveos.workflow.v1.ExecutionReceipt buildPartial() {
      org.weaveos.workflow.v1.ExecutionReceipt result = new org.weaveos.workflow.v1.ExecutionReceipt(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.weaveos.workflow.v1.ExecutionReceipt result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.commandId_ = commandId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.commandHash_ = commandHash_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.outcome_ = outcome_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.sequence_ = sequence_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.proofId_ = proofId_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.resultHash_ = resultHash_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.resultBytes_ = resultBytes_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.weaveos.workflow.v1.ExecutionReceipt) {
        return mergeFrom((org.weaveos.workflow.v1.ExecutionReceipt)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.weaveos.workflow.v1.ExecutionReceipt other) {
      if (other == org.weaveos.workflow.v1.ExecutionReceipt.getDefaultInstance()) return this;
      if (!other.getCommandId().isEmpty()) {
        commandId_ = other.commandId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getCommandHash() != com.google.protobuf.ByteString.EMPTY) {
        setCommandHash(other.getCommandHash());
      }
      if (!other.getOutcome().isEmpty()) {
        outcome_ = other.outcome_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getSequence() != 0L) {
        setSequence(other.getSequence());
      }
      if (!other.getProofId().isEmpty()) {
        proofId_ = other.proofId_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.getResultHash() != com.google.protobuf.ByteString.EMPTY) {
        setResultHash(other.getResultHash());
      }
      if (other.getResultBytes() != com.google.protobuf.ByteString.EMPTY) {
        setResultBytes(other.getResultBytes());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              commandId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              commandHash_ = input.readBytes();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              outcome_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              sequence_ = input.readUInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              proofId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              resultHash_ = input.readBytes();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              resultBytes_ = input.readBytes();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object commandId_ = "";
    /**
     * <code>string command_id = 1;</code>
     * @return The commandId.
     */
    public java.lang.String getCommandId() {
      java.lang.Object ref = commandId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        commandId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string command_id = 1;</code>
     * @return The bytes for commandId.
     */
    public com.google.protobuf.ByteString
        getCommandIdBytes() {
      java.lang.Object ref = commandId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        commandId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string command_id = 1;</code>
     * @param value The commandId to set.
     * @return This builder for chaining.
     */
    public Builder setCommandId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      commandId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string command_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCommandId() {
      commandId_ = getDefaultInstance().getCommandId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string command_id = 1;</code>
     * @param value The bytes for commandId to set.
     * @return This builder for chaining.
     */
    public Builder setCommandIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      commandId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString commandHash_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes command_hash = 2;</code>
     * @return The commandHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getCommandHash() {
      return commandHash_;
    }
    /**
     * <code>bytes command_hash = 2;</code>
     * @param value The commandHash to set.
     * @return This builder for chaining.
     */
    public Builder setCommandHash(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      commandHash_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>bytes command_hash = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCommandHash() {
      bitField0_ = (bitField0_ & ~0x00000002);
      commandHash_ = getDefaultInstance().getCommandHash();
      onChanged();
      return this;
    }

    private java.lang.Object outcome_ = "";
    /**
     * <code>string outcome = 3;</code>
     * @return The outcome.
     */
    public java.lang.String getOutcome() {
      java.lang.Object ref = outcome_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        outcome_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string outcome = 3;</code>
     * @return The bytes for outcome.
     */
    public com.google.protobuf.ByteString
        getOutcomeBytes() {
      java.lang.Object ref = outcome_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        outcome_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string outcome = 3;</code>
     * @param value The outcome to set.
     * @return This builder for chaining.
     */
    public Builder setOutcome(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      outcome_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string outcome = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearOutcome() {
      outcome_ = getDefaultInstance().getOutcome();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string outcome = 3;</code>
     * @param value The bytes for outcome to set.
     * @return This builder for chaining.
     */
    public Builder setOutcomeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      outcome_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private long sequence_ ;
    /**
     * <code>uint64 sequence = 4;</code>
     * @return The sequence.
     */
    @java.lang.Override
    public long getSequence() {
      return sequence_;
    }
    /**
     * <code>uint64 sequence = 4;</code>
     * @param value The sequence to set.
     * @return This builder for chaining.
     */
    public Builder setSequence(long value) {

      sequence_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 sequence = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSequence() {
      bitField0_ = (bitField0_ & ~0x00000008);
      sequence_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object proofId_ = "";
    /**
     * <code>string proof_id = 5;</code>
     * @return The proofId.
     */
    public java.lang.String getProofId() {
      java.lang.Object ref = proofId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        proofId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string proof_id = 5;</code>
     * @return The bytes for proofId.
     */
    public com.google.protobuf.ByteString
        getProofIdBytes() {
      java.lang.Object ref = proofId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        proofId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string proof_id = 5;</code>
     * @param value The proofId to set.
     * @return This builder for chaining.
     */
    public Builder setProofId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      proofId_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string proof_id = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearProofId() {
      proofId_ = getDefaultInstance().getProofId();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string proof_id = 5;</code>
     * @param value The bytes for proofId to set.
     * @return This builder for chaining.
     */
    public Builder setProofIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      proofId_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString resultHash_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes result_hash = 6;</code>
     * @return The resultHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getResultHash() {
      return resultHash_;
    }
    /**
     * <code>bytes result_hash = 6;</code>
     * @param value The resultHash to set.
     * @return This builder for chaining.
     */
    public Builder setResultHash(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      resultHash_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>bytes result_hash = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearResultHash() {
      bitField0_ = (bitField0_ & ~0x00000020);
      resultHash_ = getDefaultInstance().getResultHash();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString resultBytes_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes result_bytes = 7;</code>
     * @return The resultBytes.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getResultBytes() {
      return resultBytes_;
    }
    /**
     * <code>bytes result_bytes = 7;</code>
     * @param value The resultBytes to set.
     * @return This builder for chaining.
     */
    public Builder setResultBytes(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      resultBytes_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>bytes result_bytes = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearResultBytes() {
      bitField0_ = (bitField0_ & ~0x00000040);
      resultBytes_ = getDefaultInstance().getResultBytes();
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:weaveos.workflow.v1.ExecutionReceipt)
  }

  // @@protoc_insertion_point(class_scope:weaveos.workflow.v1.ExecutionReceipt)
  private static final org.weaveos.workflow.v1.ExecutionReceipt DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.weaveos.workflow.v1.ExecutionReceipt();
  }

  public static org.weaveos.workflow.v1.ExecutionReceipt getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExecutionReceipt>
      PARSER = new com.google.protobuf.AbstractParser<ExecutionReceipt>() {
    @java.lang.Override
    public ExecutionReceipt parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ExecutionReceipt> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ExecutionReceipt> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.weaveos.workflow.v1.ExecutionReceipt getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

