// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weaveos/workflow/v1/execution.proto

// Protobuf Java Version: 3.25.9
package org.weaveos.workflow.v1;

public interface ExecutionReceiptOrBuilder extends
    // @@protoc_insertion_point(interface_extends:weaveos.workflow.v1.ExecutionReceipt)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string command_id = 1;</code>
   * @return The commandId.
   */
  java.lang.String getCommandId();
  /**
   * <code>string command_id = 1;</code>
   * @return The bytes for commandId.
   */
  com.google.protobuf.ByteString
      getCommandIdBytes();

  /**
   * <code>bytes command_hash = 2;</code>
   * @return The commandHash.
   */
  com.google.protobuf.ByteString getCommandHash();

  /**
   * <code>string outcome = 3;</code>
   * @return The outcome.
   */
  java.lang.String getOutcome();
  /**
   * <code>string outcome = 3;</code>
   * @return The bytes for outcome.
   */
  com.google.protobuf.ByteString
      getOutcomeBytes();

  /**
   * <code>uint64 sequence = 4;</code>
   * @return The sequence.
   */
  long getSequence();

  /**
   * <code>string proof_id = 5;</code>
   * @return The proofId.
   */
  java.lang.String getProofId();
  /**
   * <code>string proof_id = 5;</code>
   * @return The bytes for proofId.
   */
  com.google.protobuf.ByteString
      getProofIdBytes();

  /**
   * <code>bytes result_hash = 6;</code>
   * @return The resultHash.
   */
  com.google.protobuf.ByteString getResultHash();

  /**
   * <code>bytes result_bytes = 7;</code>
   * @return The resultBytes.
   */
  com.google.protobuf.ByteString getResultBytes();
}
