// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weaveos/workflow/v1/deployment.proto

// Protobuf Java Version: 3.25.9
package org.weaveos.workflow.v1;

public interface DeployRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:weaveos.workflow.v1.DeployRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string app_id = 1;</code>
   * @return The appId.
   */
  java.lang.String getAppId();
  /**
   * <code>string app_id = 1;</code>
   * @return The bytes for appId.
   */
  com.google.protobuf.ByteString
      getAppIdBytes();

  /**
   * <code>string flow_id = 2;</code>
   * @return The flowId.
   */
  java.lang.String getFlowId();
  /**
   * <code>string flow_id = 2;</code>
   * @return The bytes for flowId.
   */
  com.google.protobuf.ByteString
      getFlowIdBytes();

  /**
   * <code>string version_id = 3;</code>
   * @return The versionId.
   */
  java.lang.String getVersionId();
  /**
   * <code>string version_id = 3;</code>
   * @return The bytes for versionId.
   */
  com.google.protobuf.ByteString
      getVersionIdBytes();

  /**
   * <code>uint64 version = 4;</code>
   * @return The version.
   */
  long getVersion();

  /**
   * <code>bytes bpmn_xml = 5;</code>
   * @return The bpmnXml.
   */
  com.google.protobuf.ByteString getBpmnXml();
}
