// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weaveos/workflow/v1/deployment.proto

// Protobuf Java Version: 3.25.9
package org.weaveos.workflow.v1;

public final class Deployment {
  private Deployment() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_weaveos_workflow_v1_DeployRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_weaveos_workflow_v1_DeployRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_weaveos_workflow_v1_DeploymentReceipt_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_weaveos_workflow_v1_DeploymentReceipt_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_weaveos_workflow_v1_LookupRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_weaveos_workflow_v1_LookupRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_weaveos_workflow_v1_NotObserved_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_weaveos_workflow_v1_NotObserved_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_weaveos_workflow_v1_LookupResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_weaveos_workflow_v1_LookupResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$weaveos/workflow/v1/deployment.proto\022\023" +
      "weaveos.workflow.v1\"g\n\rDeployRequest\022\016\n\006" +
      "app_id\030\001 \001(\t\022\017\n\007flow_id\030\002 \001(\t\022\022\n\nversion" +
      "_id\030\003 \001(\t\022\017\n\007version\030\004 \001(\004\022\020\n\010bpmn_xml\030\005" +
      " \001(\014\"\253\001\n\021DeploymentReceipt\022\016\n\006app_id\030\001 \001" +
      "(\t\022\017\n\007flow_id\030\002 \001(\t\022\022\n\nversion_id\030\003 \001(\t\022" +
      "\017\n\007version\030\004 \001(\004\022\023\n\013bpmn_sha256\030\005 \001(\t\022\034\n" +
      "\024engine_deployment_id\030\006 \001(\t\022\035\n\025process_d" +
      "efinition_id\030\007 \001(\t\"j\n\rLookupRequest\022\016\n\006a" +
      "pp_id\030\001 \001(\t\022\017\n\007flow_id\030\002 \001(\t\022\022\n\nversion_" +
      "id\030\003 \001(\t\022\017\n\007version\030\004 \001(\004\022\023\n\013bpmn_sha256" +
      "\030\005 \001(\t\"\r\n\013NotObserved\"\221\001\n\016LookupResponse" +
      "\022;\n\tconfirmed\030\001 \001(\0132&.weaveos.workflow.v" +
      "1.DeploymentReceiptH\000\0228\n\014not_observed\030\002 " +
      "\001(\0132 .weaveos.workflow.v1.NotObservedH\000B" +
      "\010\n\006result2\274\001\n\021DeploymentService\022T\n\006Deplo" +
      "y\022\".weaveos.workflow.v1.DeployRequest\032&." +
      "weaveos.workflow.v1.DeploymentReceipt\022Q\n" +
      "\006Lookup\022\".weaveos.workflow.v1.LookupRequ" +
      "est\032#.weaveos.workflow.v1.LookupResponse" +
      "B\\\n\027org.weaveos.workflow.v1P\001Z?github.co" +
      "m/Hubujiu/WeaveOS/services/bff/internal/" +
      "workflowrpc/pbb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_weaveos_workflow_v1_DeployRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_weaveos_workflow_v1_DeployRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_weaveos_workflow_v1_DeployRequest_descriptor,
        new java.lang.String[] { "AppId", "FlowId", "VersionId", "Version", "BpmnXml", });
    internal_static_weaveos_workflow_v1_DeploymentReceipt_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_weaveos_workflow_v1_DeploymentReceipt_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_weaveos_workflow_v1_DeploymentReceipt_descriptor,
        new java.lang.String[] { "AppId", "FlowId", "VersionId", "Version", "BpmnSha256", "EngineDeploymentId", "ProcessDefinitionId", });
    internal_static_weaveos_workflow_v1_LookupRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_weaveos_workflow_v1_LookupRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_weaveos_workflow_v1_LookupRequest_descriptor,
        new java.lang.String[] { "AppId", "FlowId", "VersionId", "Version", "BpmnSha256", });
    internal_static_weaveos_workflow_v1_NotObserved_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_weaveos_workflow_v1_NotObserved_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_weaveos_workflow_v1_NotObserved_descriptor,
        new java.lang.String[] { });
    internal_static_weaveos_workflow_v1_LookupResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_weaveos_workflow_v1_LookupResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_weaveos_workflow_v1_LookupResponse_descriptor,
        new java.lang.String[] { "Confirmed", "NotObserved", "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
