// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weaveos/workflow/v1/execution.proto

// Protobuf Java Version: 3.25.9
package org.weaveos.workflow.v1;

public interface ExecutionLookupRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:weaveos.workflow.v1.ExecutionLookupRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string command_id = 1;</code>
   * @return The commandId.
   */
  java.lang.String getCommandId();
  /**
   * <code>string command_id = 1;</code>
   * @return The bytes for commandId.
   */
  com.google.protobuf.ByteString
      getCommandIdBytes();

  /**
   * <code>bytes command_hash = 2;</code>
   * @return The commandHash.
   */
  com.google.protobuf.ByteString getCommandHash();
}
