// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weaveos/workflow/v1/execution.proto

// Protobuf Java Version: 3.25.9
package org.weaveos.workflow.v1;

public interface ExecutionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:weaveos.workflow.v1.ExecutionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes command_envelope = 1;</code>
   * @return The commandEnvelope.
   */
  com.google.protobuf.ByteString getCommandEnvelope();

  /**
   * <code>bytes payload = 2;</code>
   * @return The payload.
   */
  com.google.protobuf.ByteString getPayload();
}
