// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weaveos/workflow/v1/execution.proto

// Protobuf Java Version: 3.25.9
package org.weaveos.workflow.v1;

/**
 * Protobuf type {@code weaveos.workflow.v1.ExecutionLookupResponse}
 */
public final class ExecutionLookupResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:weaveos.workflow.v1.ExecutionLookupResponse)
    ExecutionLookupResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ExecutionLookupResponse.newBuilder() to construct.
  private ExecutionLookupResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ExecutionLookupResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ExecutionLookupResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.weaveos.workflow.v1.Execution.internal_static_weaveos_workflow_v1_ExecutionLookupResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.weaveos.workflow.v1.Execution.internal_static_weaveos_workflow_v1_ExecutionLookupResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.weaveos.workflow.v1.ExecutionLookupResponse.class, org.weaveos.workflow.v1.ExecutionLookupResponse.Builder.class);
  }

  private int resultCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object result_;
  public enum ResultCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    CONFIRMED(1),
    NOT_OBSERVED(2),
    RESULT_NOT_SET(0);
    private final int value;
    private ResultCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ResultCase valueOf(int value) {
      return forNumber(value);
    }

    public static ResultCase forNumber(int value) {
      switch (value) {
        case 1: return CONFIRMED;
        case 2: return NOT_OBSERVED;
        case 0: return RESULT_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ResultCase
  getResultCase() {
    return ResultCase.forNumber(
        resultCase_);
  }

  public static final int CONFIRMED_FIELD_NUMBER = 1;
  /**
   * <code>.weaveos.workflow.v1.ExecutionReceipt confirmed = 1;</code>
   * @return Whether the confirmed field is set.
   */
  @java.lang.Override
  public boolean hasConfirmed() {
    return resultCase_ == 1;
  }
  /**
   * <code>.weaveos.workflow.v1.ExecutionReceipt confirmed = 1;</code>
   * @return The confirmed.
   */
  @java.lang.Override
  public org.weaveos.workflow.v1.ExecutionReceipt getConfirmed() {
    if (resultCase_ == 1) {
       return (org.weaveos.workflow.v1.ExecutionReceipt) result_;
    }
    return org.weaveos.workflow.v1.ExecutionReceipt.getDefaultInstance();
  }
  /**
   * <code>.weaveos.workflow.v1.ExecutionReceipt confirmed = 1;</code>
   */
  @java.lang.Override
  public org.weaveos.workflow.v1.ExecutionReceiptOrBuilder getConfirmedOrBuilder() {
    if (resultCase_ == 1) {
       return (org.weaveos.workflow.v1.ExecutionReceipt) result_;
    }
    return org.weaveos.workflow.v1.ExecutionReceipt.getDefaultInstance();
  }

  public static final int NOT_OBSERVED_FIELD_NUMBER = 2;
  /**
   * <code>.weaveos.workflow.v1.NotObserved not_observed = 2;</code>
   * @return Whether the notObserved field is set.
   */
  @java.lang.Override
  public boolean hasNotObserved() {
    return resultCase_ == 2;
  }
  /**
   * <code>.weaveos.workflow.v1.NotObserved not_observed = 2;</code>
   * @return The notObserved.
   */
  @java.lang.Override
  public org.weaveos.workflow.v1.NotObserved getNotObserved() {
    if (resultCase_ == 2) {
       return (org.weaveos.workflow.v1.NotObserved) result_;
    }
    return org.weaveos.workflow.v1.NotObserved.getDefaultInstance();
  }
  /**
   * <code>.weaveos.workflow.v1.NotObserved not_observed = 2;</code>
   */
  @java.lang.Override
  public org.weaveos.workflow.v1.NotObservedOrBuilder getNotObservedOrBuilder() {
    if (resultCase_ == 2) {
       return (org.weaveos.workflow.v1.NotObserved) result_;
    }
    return org.weaveos.workflow.v1.NotObserved.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (resultCase_ == 1) {
      output.writeMessage(1, (org.weaveos.workflow.v1.ExecutionReceipt) result_);
    }
    if (resultCase_ == 2) {
      output.writeMessage(2, (org.weaveos.workflow.v1.NotObserved) result_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (resultCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (org.weaveos.workflow.v1.ExecutionReceipt) result_);
    }
    if (resultCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (org.weaveos.workflow.v1.NotObserved) result_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.weaveos.workflow.v1.ExecutionLookupResponse)) {
      return super.equals(obj);
    }
    org.weaveos.workflow.v1.ExecutionLookupResponse other = (org.weaveos.workflow.v1.ExecutionLookupResponse) obj;

    if (!getResultCase().equals(other.getResultCase())) return false;
    switch (resultCase_) {
      case 1:
        if (!getConfirmed()
            .equals(other.getConfirmed())) return false;
        break;
      case 2:
        if (!getNotObserved()
            .equals(other.getNotObserved())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (resultCase_) {
      case 1:
        hash = (37 * hash) + CONFIRMED_FIELD_NUMBER;
        hash = (53 * hash) + getConfirmed().hashCode();
        break;
      case 2:
        hash = (37 * hash) + NOT_OBSERVED_FIELD_NUMBER;
        hash = (53 * hash) + getNotObserved().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.weaveos.workflow.v1.ExecutionLookupResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.weaveos.workflow.v1.ExecutionLookupResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.weaveos.workflow.v1.ExecutionLookupResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.weaveos.workflow.v1.ExecutionLookupResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.weaveos.workflow.v1.ExecutionLookupResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.weaveos.workflow.v1.ExecutionLookupResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.weaveos.workflow.v1.ExecutionLookupResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.weaveos.workflow.v1.ExecutionLookupResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.weaveos.workflow.v1.ExecutionLookupResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.weaveos.workflow.v1.ExecutionLookupResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.weaveos.workflow.v1.ExecutionLookupResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.weaveos.workflow.v1.ExecutionLookupResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.weaveos.workflow.v1.ExecutionLookupResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code weaveos.workflow.v1.ExecutionLookupResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:weaveos.workflow.v1.ExecutionLookupResponse)
      org.weaveos.workflow.v1.ExecutionLookupResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.weaveos.workflow.v1.Execution.internal_static_weaveos_workflow_v1_ExecutionLookupResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.weaveos.workflow.v1.Execution.internal_static_weaveos_workflow_v1_ExecutionLookupResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.weaveos.workflow.v1.ExecutionLookupResponse.class, org.weaveos.workflow.v1.ExecutionLookupResponse.Builder.class);
    }

    // Construct using org.weaveos.workflow.v1.ExecutionLookupResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (confirmedBuilder_ != null) {
        confirmedBuilder_.clear();
      }
      if (notObservedBuilder_ != null) {
        notObservedBuilder_.clear();
      }
      resultCase_ = 0;
      result_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.weaveos.workflow.v1.Execution.internal_static_weaveos_workflow_v1_ExecutionLookupResponse_descriptor;
    }

    @java.lang.Override
    public org.weaveos.workflow.v1.ExecutionLookupResponse getDefaultInstanceForType() {
      return org.weaveos.workflow.v1.ExecutionLookupResponse.getDefaultInstance();
    }

    @java.lang.Override
    public org.weaveos.workflow.v1.ExecutionLookupResponse build() {
      org.weaveos.workflow.v1.ExecutionLookupResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.weaveos.workflow.v1.ExecutionLookupResponse buildPartial() {
      org.weaveos.workflow.v1.ExecutionLookupResponse result = new org.weaveos.workflow.v1.ExecutionLookupResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(org.weaveos.workflow.v1.ExecutionLookupResponse result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(org.weaveos.workflow.v1.ExecutionLookupResponse result) {
      result.resultCase_ = resultCase_;
      result.result_ = this.result_;
      if (resultCase_ == 1 &&
          confirmedBuilder_ != null) {
        result.result_ = confirmedBuilder_.build();
      }
      if (resultCase_ == 2 &&
          notObservedBuilder_ != null) {
        result.result_ = notObservedBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.weaveos.workflow.v1.ExecutionLookupResponse) {
        return mergeFrom((org.weaveos.workflow.v1.ExecutionLookupResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.weaveos.workflow.v1.ExecutionLookupResponse other) {
      if (other == org.weaveos.workflow.v1.ExecutionLookupResponse.getDefaultInstance()) return this;
      switch (other.getResultCase()) {
        case CONFIRMED: {
          mergeConfirmed(other.getConfirmed());
          break;
        }
        case NOT_OBSERVED: {
          mergeNotObserved(other.getNotObserved());
          break;
        }
        case RESULT_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getConfirmedFieldBuilder().getBuilder(),
                  extensionRegistry);
              resultCase_ = 1;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getNotObservedFieldBuilder().getBuilder(),
                  extensionRegistry);
              resultCase_ = 2;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int resultCase_ = 0;
    private java.lang.Object result_;
    public ResultCase
        getResultCase() {
      return ResultCase.forNumber(
          resultCase_);
    }

    public Builder clearResult() {
      resultCase_ = 0;
      result_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilderV3<
        org.weaveos.workflow.v1.ExecutionReceipt, org.weaveos.workflow.v1.ExecutionReceipt.Builder, org.weaveos.workflow.v1.ExecutionReceiptOrBuilder> confirmedBuilder_;
    /**
     * <code>.weaveos.workflow.v1.ExecutionReceipt confirmed = 1;</code>
     * @return Whether the confirmed field is set.
     */
    @java.lang.Override
    public boolean hasConfirmed() {
      return resultCase_ == 1;
    }
    /**
     * <code>.weaveos.workflow.v1.ExecutionReceipt confirmed = 1;</code>
     * @return The confirmed.
     */
    @java.lang.Override
    public org.weaveos.workflow.v1.ExecutionReceipt getConfirmed() {
      if (confirmedBuilder_ == null) {
        if (resultCase_ == 1) {
          return (org.weaveos.workflow.v1.ExecutionReceipt) result_;
        }
        return org.weaveos.workflow.v1.ExecutionReceipt.getDefaultInstance();
      } else {
        if (resultCase_ == 1) {
          return confirmedBuilder_.getMessage();
        }
        return org.weaveos.workflow.v1.ExecutionReceipt.getDefaultInstance();
      }
    }
    /**
     * <code>.weaveos.workflow.v1.ExecutionReceipt confirmed = 1;</code>
     */
    public Builder setConfirmed(org.weaveos.workflow.v1.ExecutionReceipt value) {
      if (confirmedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        result_ = value;
        onChanged();
      } else {
        confirmedBuilder_.setMessage(value);
      }
      resultCase_ = 1;
      return this;
    }
    /**
     * <code>.weaveos.workflow.v1.ExecutionReceipt confirmed = 1;</code>
     */
    public Builder setConfirmed(
        org.weaveos.workflow.v1.ExecutionReceipt.Builder builderForValue) {
      if (confirmedBuilder_ == null) {
        result_ = builderForValue.build();
        onChanged();
      } else {
        confirmedBuilder_.setMessage(builderForValue.build());
      }
      resultCase_ = 1;
      return this;
    }
    /**
     * <code>.weaveos.workflow.v1.ExecutionReceipt confirmed = 1;</code>
     */
    public Builder mergeConfirmed(org.weaveos.workflow.v1.ExecutionReceipt value) {
      if (confirmedBuilder_ == null) {
        if (resultCase_ == 1 &&
            result_ != org.weaveos.workflow.v1.ExecutionReceipt.getDefaultInstance()) {
          result_ = org.weaveos.workflow.v1.ExecutionReceipt.newBuilder((org.weaveos.workflow.v1.ExecutionReceipt) result_)
              .mergeFrom(value).buildPartial();
        } else {
          result_ = value;
        }
        onChanged();
      } else {
        if (resultCase_ == 1) {
          confirmedBuilder_.mergeFrom(value);
        } else {
          confirmedBuilder_.setMessage(value);
        }
      }
      resultCase_ = 1;
      return this;
    }
    /**
     * <code>.weaveos.workflow.v1.ExecutionReceipt confirmed = 1;</code>
     */
    public Builder clearConfirmed() {
      if (confirmedBuilder_ == null) {
        if (resultCase_ == 1) {
          resultCase_ = 0;
          result_ = null;
          onChanged();
        }
      } else {
        if (resultCase_ == 1) {
          resultCase_ = 0;
          result_ = null;
        }
        confirmedBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.weaveos.workflow.v1.ExecutionReceipt confirmed = 1;</code>
     */
    public org.weaveos.workflow.v1.ExecutionReceipt.Builder getConfirmedBuilder() {
      return getConfirmedFieldBuilder().getBuilder();
    }
    /**
     * <code>.weaveos.workflow.v1.ExecutionReceipt confirmed = 1;</code>
     */
    @java.lang.Override
    public org.weaveos.workflow.v1.ExecutionReceiptOrBuilder getConfirmedOrBuilder() {
      if ((resultCase_ == 1) && (confirmedBuilder_ != null)) {
        return confirmedBuilder_.getMessageOrBuilder();
      } else {
        if (resultCase_ == 1) {
          return (org.weaveos.workflow.v1.ExecutionReceipt) result_;
        }
        return org.weaveos.workflow.v1.ExecutionReceipt.getDefaultInstance();
      }
    }
    /**
     * <code>.weaveos.workflow.v1.ExecutionReceipt confirmed = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.weaveos.workflow.v1.ExecutionReceipt, org.weaveos.workflow.v1.ExecutionReceipt.Builder, org.weaveos.workflow.v1.ExecutionReceiptOrBuilder> 
        getConfirmedFieldBuilder() {
      if (confirmedBuilder_ == null) {
        if (!(resultCase_ == 1)) {
          result_ = org.weaveos.workflow.v1.ExecutionReceipt.getDefaultInstance();
        }
        confirmedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.weaveos.workflow.v1.ExecutionReceipt, org.weaveos.workflow.v1.ExecutionReceipt.Builder, org.weaveos.workflow.v1.ExecutionReceiptOrBuilder>(
                (org.weaveos.workflow.v1.ExecutionReceipt) result_,
                getParentForChildren(),
                isClean());
        result_ = null;
      }
      resultCase_ = 1;
      onChanged();
      return confirmedBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        org.weaveos.workflow.v1.NotObserved, org.weaveos.workflow.v1.NotObserved.Builder, org.weaveos.workflow.v1.NotObservedOrBuilder> notObservedBuilder_;
    /**
     * <code>.weaveos.workflow.v1.NotObserved not_observed = 2;</code>
     * @return Whether the notObserved field is set.
     */
    @java.lang.Override
    public boolean hasNotObserved() {
      return resultCase_ == 2;
    }
    /**
     * <code>.weaveos.workflow.v1.NotObserved not_observed = 2;</code>
     * @return The notObserved.
     */
    @java.lang.Override
    public org.weaveos.workflow.v1.NotObserved getNotObserved() {
      if (notObservedBuilder_ == null) {
        if (resultCase_ == 2) {
          return (org.weaveos.workflow.v1.NotObserved) result_;
        }
        return org.weaveos.workflow.v1.NotObserved.getDefaultInstance();
      } else {
        if (resultCase_ == 2) {
          return notObservedBuilder_.getMessage();
        }
        return org.weaveos.workflow.v1.NotObserved.getDefaultInstance();
      }
    }
    /**
     * <code>.weaveos.workflow.v1.NotObserved not_observed = 2;</code>
     */
    public Builder setNotObserved(org.weaveos.workflow.v1.NotObserved value) {
      if (notObservedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        result_ = value;
        onChanged();
      } else {
        notObservedBuilder_.setMessage(value);
      }
      resultCase_ = 2;
      return this;
    }
    /**
     * <code>.weaveos.workflow.v1.NotObserved not_observed = 2;</code>
     */
    public Builder setNotObserved(
        org.weaveos.workflow.v1.NotObserved.Builder builderForValue) {
      if (notObservedBuilder_ == null) {
        result_ = builderForValue.build();
        onChanged();
      } else {
        notObservedBuilder_.setMessage(builderForValue.build());
      }
      resultCase_ = 2;
      return this;
    }
    /**
     * <code>.weaveos.workflow.v1.NotObserved not_observed = 2;</code>
     */
    public Builder mergeNotObserved(org.weaveos.workflow.v1.NotObserved value) {
      if (notObservedBuilder_ == null) {
        if (resultCase_ == 2 &&
            result_ != org.weaveos.workflow.v1.NotObserved.getDefaultInstance()) {
          result_ = org.weaveos.workflow.v1.NotObserved.newBuilder((org.weaveos.workflow.v1.NotObserved) result_)
              .mergeFrom(value).buildPartial();
        } else {
          result_ = value;
        }
        onChanged();
      } else {
        if (resultCase_ == 2) {
          notObservedBuilder_.mergeFrom(value);
        } else {
          notObservedBuilder_.setMessage(value);
        }
      }
      resultCase_ = 2;
      return this;
    }
    /**
     * <code>.weaveos.workflow.v1.NotObserved not_observed = 2;</code>
     */
    public Builder clearNotObserved() {
      if (notObservedBuilder_ == null) {
        if (resultCase_ == 2) {
          resultCase_ = 0;
          result_ = null;
          onChanged();
        }
      } else {
        if (resultCase_ == 2) {
          resultCase_ = 0;
          result_ = null;
        }
        notObservedBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.weaveos.workflow.v1.NotObserved not_observed = 2;</code>
     */
    public org.weaveos.workflow.v1.NotObserved.Builder getNotObservedBuilder() {
      return getNotObservedFieldBuilder().getBuilder();
    }
    /**
     * <code>.weaveos.workflow.v1.NotObserved not_observed = 2;</code>
     */
    @java.lang.Override
    public org.weaveos.workflow.v1.NotObservedOrBuilder getNotObservedOrBuilder() {
      if ((resultCase_ == 2) && (notObservedBuilder_ != null)) {
        return notObservedBuilder_.getMessageOrBuilder();
      } else {
        if (resultCase_ == 2) {
          return (org.weaveos.workflow.v1.NotObserved) result_;
        }
        return org.weaveos.workflow.v1.NotObserved.getDefaultInstance();
      }
    }
    /**
     * <code>.weaveos.workflow.v1.NotObserved not_observed = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.weaveos.workflow.v1.NotObserved, org.weaveos.workflow.v1.NotObserved.Builder, org.weaveos.workflow.v1.NotObservedOrBuilder> 
        getNotObservedFieldBuilder() {
      if (notObservedBuilder_ == null) {
        if (!(resultCase_ == 2)) {
          result_ = org.weaveos.workflow.v1.NotObserved.getDefaultInstance();
        }
        notObservedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.weaveos.workflow.v1.NotObserved, org.weaveos.workflow.v1.NotObserved.Builder, org.weaveos.workflow.v1.NotObservedOrBuilder>(
                (org.weaveos.workflow.v1.NotObserved) result_,
                getParentForChildren(),
                isClean());
        result_ = null;
      }
      resultCase_ = 2;
      onChanged();
      return notObservedBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:weaveos.workflow.v1.ExecutionLookupResponse)
  }

  // @@protoc_insertion_point(class_scope:weaveos.workflow.v1.ExecutionLookupResponse)
  private static final org.weaveos.workflow.v1.ExecutionLookupResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.weaveos.workflow.v1.ExecutionLookupResponse();
  }

  public static org.weaveos.workflow.v1.ExecutionLookupResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExecutionLookupResponse>
      PARSER = new com.google.protobuf.AbstractParser<ExecutionLookupResponse>() {
    @java.lang.Override
    public ExecutionLookupResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ExecutionLookupResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ExecutionLookupResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.weaveos.workflow.v1.ExecutionLookupResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

