// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weaveos/workflow/v1/deployment.proto

// Protobuf Java Version: 3.25.9
package org.weaveos.workflow.v1;

public interface FlowDeletionLookupResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:weaveos.workflow.v1.FlowDeletionLookupResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.weaveos.workflow.v1.FlowDeletionReceipt confirmed = 1;</code>
   * @return Whether the confirmed field is set.
   */
  boolean hasConfirmed();
  /**
   * <code>.weaveos.workflow.v1.FlowDeletionReceipt confirmed = 1;</code>
   * @return The confirmed.
   */
  org.weaveos.workflow.v1.FlowDeletionReceipt getConfirmed();
  /**
   * <code>.weaveos.workflow.v1.FlowDeletionReceipt confirmed = 1;</code>
   */
  org.weaveos.workflow.v1.FlowDeletionReceiptOrBuilder getConfirmedOrBuilder();

  /**
   * <code>.weaveos.workflow.v1.NotObserved not_observed = 2;</code>
   * @return Whether the notObserved field is set.
   */
  boolean hasNotObserved();
  /**
   * <code>.weaveos.workflow.v1.NotObserved not_observed = 2;</code>
   * @return The notObserved.
   */
  org.weaveos.workflow.v1.NotObserved getNotObserved();
  /**
   * <code>.weaveos.workflow.v1.NotObserved not_observed = 2;</code>
   */
  org.weaveos.workflow.v1.NotObservedOrBuilder getNotObservedOrBuilder();

  org.weaveos.workflow.v1.FlowDeletionLookupResponse.ResultCase getResultCase();
}
