// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weaveos/workflow/v1/deployment.proto

// Protobuf Java Version: 3.25.9
package org.weaveos.workflow.v1;

public interface FlowDeletionReceiptOrBuilder extends
    // @@protoc_insertion_point(interface_extends:weaveos.workflow.v1.FlowDeletionReceipt)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string app_id = 1;</code>
   * @return The appId.
   */
  java.lang.String getAppId();
  /**
   * <code>string app_id = 1;</code>
   * @return The bytes for appId.
   */
  com.google.protobuf.ByteString
      getAppIdBytes();

  /**
   * <code>string flow_id = 2;</code>
   * @return The flowId.
   */
  java.lang.String getFlowId();
  /**
   * <code>string flow_id = 2;</code>
   * @return The bytes for flowId.
   */
  com.google.protobuf.ByteString
      getFlowIdBytes();

  /**
   * <code>string operation_id = 3;</code>
   * @return The operationId.
   */
  java.lang.String getOperationId();
  /**
   * <code>string operation_id = 3;</code>
   * @return The bytes for operationId.
   */
  com.google.protobuf.ByteString
      getOperationIdBytes();

  /**
   * <code>uint64 deleted_versions = 4;</code>
   * @return The deletedVersions.
   */
  long getDeletedVersions();

  /**
   * <code>int64 deleted_at_seconds = 5;</code>
   * @return The deletedAtSeconds.
   */
  long getDeletedAtSeconds();

  /**
   * <code>int32 deleted_at_nanos = 6;</code>
   * @return The deletedAtNanos.
   */
  int getDeletedAtNanos();
}
