// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weaveos/workflow/v1/deployment.proto

// Protobuf Java Version: 3.25.9
package org.weaveos.workflow.v1;

/**
 * Protobuf type {@code weaveos.workflow.v1.FlowDeletionReceipt}
 */
public final class FlowDeletionReceipt extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:weaveos.workflow.v1.FlowDeletionReceipt)
    FlowDeletionReceiptOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FlowDeletionReceipt.newBuilder() to construct.
  private FlowDeletionReceipt(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FlowDeletionReceipt() {
    appId_ = "";
    flowId_ = "";
    operationId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FlowDeletionReceipt();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.weaveos.workflow.v1.Deployment.internal_static_weaveos_workflow_v1_FlowDeletionReceipt_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.weaveos.workflow.v1.Deployment.internal_static_weaveos_workflow_v1_FlowDeletionReceipt_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.weaveos.workflow.v1.FlowDeletionReceipt.class, org.weaveos.workflow.v1.FlowDeletionReceipt.Builder.class);
  }

  public static final int APP_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object appId_ = "";
  /**
   * <code>string app_id = 1;</code>
   * @return The appId.
   */
  @java.lang.Override
  public java.lang.String getAppId() {
    java.lang.Object ref = appId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      appId_ = s;
      return s;
    }
  }
  /**
   * <code>string app_id = 1;</code>
   * @return The bytes for appId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAppIdBytes() {
    java.lang.Object ref = appId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      appId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FLOW_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object flowId_ = "";
  /**
   * <code>string flow_id = 2;</code>
   * @return The flowId.
   */
  @java.lang.Override
  public java.lang.String getFlowId() {
    java.lang.Object ref = flowId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      flowId_ = s;
      return s;
    }
  }
  /**
   * <code>string flow_id = 2;</code>
   * @return The bytes for flowId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFlowIdBytes() {
    java.lang.Object ref = flowId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      flowId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OPERATION_ID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object operationId_ = "";
  /**
   * <code>string operation_id = 3;</code>
   * @return The operationId.
   */
  @java.lang.Override
  public java.lang.String getOperationId() {
    java.lang.Object ref = operationId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      operationId_ = s;
      return s;
    }
  }
  /**
   * <code>string operation_id = 3;</code>
   * @return The bytes for operationId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOperationIdBytes() {
    java.lang.Object ref = operationId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      operationId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DELETED_VERSIONS_FIELD_NUMBER = 4;
  private long deletedVersions_ = 0L;
  /**
   * <code>uint64 deleted_versions = 4;</code>
   * @return The deletedVersions.
   */
  @java.lang.Override
  public long getDeletedVersions() {
    return deletedVersions_;
  }

  public static final int DELETED_AT_SECONDS_FIELD_NUMBER = 5;
  private long deletedAtSeconds_ = 0L;
  /**
   * <code>int64 deleted_at_seconds = 5;</code>
   * @return The deletedAtSeconds.
   */
  @java.lang.Override
  public long getDeletedAtSeconds() {
    return deletedAtSeconds_;
  }

  public static final int DELETED_AT_NANOS_FIELD_NUMBER = 6;
  private int deletedAtNanos_ = 0;
  /**
   * <code>int32 deleted_at_nanos = 6;</code>
   * @return The deletedAtNanos.
   */
  @java.lang.Override
  public int getDeletedAtNanos() {
    return deletedAtNanos_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(appId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, appId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(flowId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, flowId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(operationId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, operationId_);
    }
    if (deletedVersions_ != 0L) {
      output.writeUInt64(4, deletedVersions_);
    }
    if (deletedAtSeconds_ != 0L) {
      output.writeInt64(5, deletedAtSeconds_);
    }
    if (deletedAtNanos_ != 0) {
      output.writeInt32(6, deletedAtNanos_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(appId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, appId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(flowId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, flowId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(operationId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, operationId_);
    }
    if (deletedVersions_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(4, deletedVersions_);
    }
    if (deletedAtSeconds_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, deletedAtSeconds_);
    }
    if (deletedAtNanos_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, deletedAtNanos_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.weaveos.workflow.v1.FlowDeletionReceipt)) {
      return super.equals(obj);
    }
    org.weaveos.workflow.v1.FlowDeletionReceipt other = (org.weaveos.workflow.v1.FlowDeletionReceipt) obj;

    if (!getAppId()
        .equals(other.getAppId())) return false;
    if (!getFlowId()
        .equals(other.getFlowId())) return false;
    if (!getOperationId()
        .equals(other.getOperationId())) return false;
    if (getDeletedVersions()
        != other.getDeletedVersions()) return false;
    if (getDeletedAtSeconds()
        != other.getDeletedAtSeconds()) return false;
    if (getDeletedAtNanos()
        != other.getDeletedAtNanos()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + APP_ID_FIELD_NUMBER;
    hash = (53 * hash) + getAppId().hashCode();
    hash = (37 * hash) + FLOW_ID_FIELD_NUMBER;
    hash = (53 * hash) + getFlowId().hashCode();
    hash = (37 * hash) + OPERATION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getOperationId().hashCode();
    hash = (37 * hash) + DELETED_VERSIONS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDeletedVersions());
    hash = (37 * hash) + DELETED_AT_SECONDS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDeletedAtSeconds());
    hash = (37 * hash) + DELETED_AT_NANOS_FIELD_NUMBER;
    hash = (53 * hash) + getDeletedAtNanos();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.weaveos.workflow.v1.FlowDeletionReceipt parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.weaveos.workflow.v1.FlowDeletionReceipt parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.weaveos.workflow.v1.FlowDeletionReceipt parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.weaveos.workflow.v1.FlowDeletionReceipt parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.weaveos.workflow.v1.FlowDeletionReceipt parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.weaveos.workflow.v1.FlowDeletionReceipt parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.weaveos.workflow.v1.FlowDeletionReceipt parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.weaveos.workflow.v1.FlowDeletionReceipt parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.weaveos.workflow.v1.FlowDeletionReceipt parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.weaveos.workflow.v1.FlowDeletionReceipt parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.weaveos.workflow.v1.FlowDeletionReceipt parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.weaveos.workflow.v1.FlowDeletionReceipt parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.weaveos.workflow.v1.FlowDeletionReceipt prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code weaveos.workflow.v1.FlowDeletionReceipt}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:weaveos.workflow.v1.FlowDeletionReceipt)
      org.weaveos.workflow.v1.FlowDeletionReceiptOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.weaveos.workflow.v1.Deployment.internal_static_weaveos_workflow_v1_FlowDeletionReceipt_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.weaveos.workflow.v1.Deployment.internal_static_weaveos_workflow_v1_FlowDeletionReceipt_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.weaveos.workflow.v1.FlowDeletionReceipt.class, org.weaveos.workflow.v1.FlowDeletionReceipt.Builder.class);
    }

    // Construct using org.weaveos.workflow.v1.FlowDeletionReceipt.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      appId_ = "";
      flowId_ = "";
      operationId_ = "";
      deletedVersions_ = 0L;
      deletedAtSeconds_ = 0L;
      deletedAtNanos_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.weaveos.workflow.v1.Deployment.internal_static_weaveos_workflow_v1_FlowDeletionReceipt_descriptor;
    }

    @java.lang.Override
    public org.weaveos.workflow.v1.FlowDeletionReceipt getDefaultInstanceForType() {
      return org.weaveos.workflow.v1.FlowDeletionReceipt.getDefaultInstance();
    }

    @java.lang.Override
    public org.weaveos.workflow.v1.FlowDeletionReceipt build() {
      org.weaveos.workflow.v1.FlowDeletionReceipt result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.weaveos.workflow.v1.FlowDeletionReceipt buildPartial() {
      org.weaveos.workflow.v1.FlowDeletionReceipt result = new org.weaveos.workflow.v1.FlowDeletionReceipt(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.weaveos.workflow.v1.FlowDeletionReceipt result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.appId_ = appId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.flowId_ = flowId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.operationId_ = operationId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.deletedVersions_ = deletedVersions_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.deletedAtSeconds_ = deletedAtSeconds_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.deletedAtNanos_ = deletedAtNanos_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.weaveos.workflow.v1.FlowDeletionReceipt) {
        return mergeFrom((org.weaveos.workflow.v1.FlowDeletionReceipt)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.weaveos.workflow.v1.FlowDeletionReceipt other) {
      if (other == org.weaveos.workflow.v1.FlowDeletionReceipt.getDefaultInstance()) return this;
      if (!other.getAppId().isEmpty()) {
        appId_ = other.appId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getFlowId().isEmpty()) {
        flowId_ = other.flowId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getOperationId().isEmpty()) {
        operationId_ = other.operationId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getDeletedVersions() != 0L) {
        setDeletedVersions(other.getDeletedVersions());
      }
      if (other.getDeletedAtSeconds() != 0L) {
        setDeletedAtSeconds(other.getDeletedAtSeconds());
      }
      if (other.getDeletedAtNanos() != 0) {
        setDeletedAtNanos(other.getDeletedAtNanos());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              appId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              flowId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              operationId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              deletedVersions_ = input.readUInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              deletedAtSeconds_ = input.readInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              deletedAtNanos_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object appId_ = "";
    /**
     * <code>string app_id = 1;</code>
     * @return The appId.
     */
    public java.lang.String getAppId() {
      java.lang.Object ref = appId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string app_id = 1;</code>
     * @return The bytes for appId.
     */
    public com.google.protobuf.ByteString
        getAppIdBytes() {
      java.lang.Object ref = appId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string app_id = 1;</code>
     * @param value The appId to set.
     * @return This builder for chaining.
     */
    public Builder setAppId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      appId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string app_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAppId() {
      appId_ = getDefaultInstance().getAppId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string app_id = 1;</code>
     * @param value The bytes for appId to set.
     * @return This builder for chaining.
     */
    public Builder setAppIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      appId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object flowId_ = "";
    /**
     * <code>string flow_id = 2;</code>
     * @return The flowId.
     */
    public java.lang.String getFlowId() {
      java.lang.Object ref = flowId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        flowId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string flow_id = 2;</code>
     * @return The bytes for flowId.
     */
    public com.google.protobuf.ByteString
        getFlowIdBytes() {
      java.lang.Object ref = flowId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        flowId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string flow_id = 2;</code>
     * @param value The flowId to set.
     * @return This builder for chaining.
     */
    public Builder setFlowId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      flowId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string flow_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFlowId() {
      flowId_ = getDefaultInstance().getFlowId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string flow_id = 2;</code>
     * @param value The bytes for flowId to set.
     * @return This builder for chaining.
     */
    public Builder setFlowIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      flowId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object operationId_ = "";
    /**
     * <code>string operation_id = 3;</code>
     * @return The operationId.
     */
    public java.lang.String getOperationId() {
      java.lang.Object ref = operationId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        operationId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string operation_id = 3;</code>
     * @return The bytes for operationId.
     */
    public com.google.protobuf.ByteString
        getOperationIdBytes() {
      java.lang.Object ref = operationId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        operationId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string operation_id = 3;</code>
     * @param value The operationId to set.
     * @return This builder for chaining.
     */
    public Builder setOperationId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      operationId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string operation_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearOperationId() {
      operationId_ = getDefaultInstance().getOperationId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string operation_id = 3;</code>
     * @param value The bytes for operationId to set.
     * @return This builder for chaining.
     */
    public Builder setOperationIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      operationId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private long deletedVersions_ ;
    /**
     * <code>uint64 deleted_versions = 4;</code>
     * @return The deletedVersions.
     */
    @java.lang.Override
    public long getDeletedVersions() {
      return deletedVersions_;
    }
    /**
     * <code>uint64 deleted_versions = 4;</code>
     * @param value The deletedVersions to set.
     * @return This builder for chaining.
     */
    public Builder setDeletedVersions(long value) {

      deletedVersions_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 deleted_versions = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeletedVersions() {
      bitField0_ = (bitField0_ & ~0x00000008);
      deletedVersions_ = 0L;
      onChanged();
      return this;
    }

    private long deletedAtSeconds_ ;
    /**
     * <code>int64 deleted_at_seconds = 5;</code>
     * @return The deletedAtSeconds.
     */
    @java.lang.Override
    public long getDeletedAtSeconds() {
      return deletedAtSeconds_;
    }
    /**
     * <code>int64 deleted_at_seconds = 5;</code>
     * @param value The deletedAtSeconds to set.
     * @return This builder for chaining.
     */
    public Builder setDeletedAtSeconds(long value) {

      deletedAtSeconds_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int64 deleted_at_seconds = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeletedAtSeconds() {
      bitField0_ = (bitField0_ & ~0x00000010);
      deletedAtSeconds_ = 0L;
      onChanged();
      return this;
    }

    private int deletedAtNanos_ ;
    /**
     * <code>int32 deleted_at_nanos = 6;</code>
     * @return The deletedAtNanos.
     */
    @java.lang.Override
    public int getDeletedAtNanos() {
      return deletedAtNanos_;
    }
    /**
     * <code>int32 deleted_at_nanos = 6;</code>
     * @param value The deletedAtNanos to set.
     * @return This builder for chaining.
     */
    public Builder setDeletedAtNanos(int value) {

      deletedAtNanos_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int32 deleted_at_nanos = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeletedAtNanos() {
      bitField0_ = (bitField0_ & ~0x00000020);
      deletedAtNanos_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:weaveos.workflow.v1.FlowDeletionReceipt)
  }

  // @@protoc_insertion_point(class_scope:weaveos.workflow.v1.FlowDeletionReceipt)
  private static final org.weaveos.workflow.v1.FlowDeletionReceipt DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.weaveos.workflow.v1.FlowDeletionReceipt();
  }

  public static org.weaveos.workflow.v1.FlowDeletionReceipt getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FlowDeletionReceipt>
      PARSER = new com.google.protobuf.AbstractParser<FlowDeletionReceipt>() {
    @java.lang.Override
    public FlowDeletionReceipt parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FlowDeletionReceipt> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FlowDeletionReceipt> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.weaveos.workflow.v1.FlowDeletionReceipt getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

