// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weaveos/workflow/v1/deployment.proto

// Protobuf Java Version: 3.25.9
package org.weaveos.workflow.v1;

public interface FlowDeletionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:weaveos.workflow.v1.FlowDeletionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string app_id = 1;</code>
   * @return The appId.
   */
  java.lang.String getAppId();
  /**
   * <code>string app_id = 1;</code>
   * @return The bytes for appId.
   */
  com.google.protobuf.ByteString
      getAppIdBytes();

  /**
   * <code>string flow_id = 2;</code>
   * @return The flowId.
   */
  java.lang.String getFlowId();
  /**
   * <code>string flow_id = 2;</code>
   * @return The bytes for flowId.
   */
  com.google.protobuf.ByteString
      getFlowIdBytes();

  /**
   * <code>string operation_id = 3;</code>
   * @return The operationId.
   */
  java.lang.String getOperationId();
  /**
   * <code>string operation_id = 3;</code>
   * @return The bytes for operationId.
   */
  com.google.protobuf.ByteString
      getOperationIdBytes();
}
