// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weaveos/workflow/v1/deployment.proto

// Protobuf Java Version: 3.25.9
package org.weaveos.workflow.v1;

public interface NotObservedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:weaveos.workflow.v1.NotObserved)
    com.google.protobuf.MessageOrBuilder {
}
